args <- commandArgs(trailingOnly = TRUE)
repo <- Sys.getenv("REPO_DIR", if (length(args)) args[[1]] else "")
lib <- Sys.getenv("CDS_DATAGRAB_R_LIB", "")
if (!nzchar(lib)) stop("CDS_DATAGRAB_R_LIB is not set; configure the external installed package library before submitting.", call.=FALSE)
.libPaths(unique(c(normalizePath(lib, winslash="/", mustWork=FALSE), .libPaths())))
cat("R version: ", R.version.string, "\n", sep="")
cat(".libPaths(): ", paste(.libPaths(), collapse=";"), "\n", sep="")
cat("R_LIBS_USER: ", Sys.getenv("R_LIBS_USER", ""), "\n", sep="")
cat("CDS_DATAGRAB_R_LIB: ", lib, "\n", sep="")
available <- requireNamespace("cdsdatagrab", quietly=TRUE)
cat("cdsdatagrab available: ", available, "\n", sep="")
if (!available) stop("Actionable preflight failure: cdsdatagrab is unavailable. Checked CDS_DATAGRAB_R_LIB and .libPaths(): ", paste(.libPaths(), collapse=";"), ". Run hpc/install_cdsdatagrab_atlas.sh.", call.=FALSE)
installed_path <- normalizePath(find.package("cdsdatagrab"), winslash="/", mustWork=TRUE)
cat("find.package(\"cdsdatagrab\"): ", installed_path, "\n", sep="")
cat("packageVersion(\"cdsdatagrab\"): ", as.character(packageVersion("cdsdatagrab")), "\n", sep="")
marker <- file.path(normalizePath(lib, winslash="/", mustWork=FALSE), ".cds-datagrab-installed-commit")
source_commit <- if (nzchar(repo)) tryCatch(trimws(system2("git", c("-C", repo, "rev-parse", "HEAD"), stdout=TRUE, stderr=FALSE)), error=function(e) "") else ""
installed_commit <- if (file.exists(marker)) trimws(readLines(marker, n=1L, warn=FALSE)) else ""
cat("source_git_commit: ", source_commit, "\n", sep="")
cat("installed_package_git_commit: ", installed_commit, "\n", sep="")
if (!nzchar(installed_commit)) stop("Installed package commit marker is missing: ", marker, ". Run hpc/install_cdsdatagrab_atlas.sh.", call.=FALSE)
if (nzchar(source_commit) && !identical(source_commit, installed_commit)) stop("Installed cdsdatagrab commit differs from source checkout. source=", source_commit, ", installed=", installed_commit, ". Rerun hpc/install_cdsdatagrab_atlas.sh.", call.=FALSE)
