make_nc4_fixture <- function(path) {
  skip_if_not_installed("ncdf4")
  lon<-ncdf4::ncdim_def("longitude","degrees_east",c(10,20)); lat<-ncdf4::ncdim_def("latitude","degrees_north",c(-1,1)); tim<-ncdf4::ncdim_def("valid_time","hours since 2026-07-01 00:00:00",c(0,24,48),unlim=FALSE); num<-ncdf4::ncdim_def("number","",as.integer(1),create_dimvar=FALSE)
  tv<-ncdf4::ncvar_def("t2m","K",list(lon,lat,tim),missval=-9999,prec="double"); nv<-ncdf4::ncvar_def("number","",list(num),prec="integer")
  nc<-ncdf4::nc_create(path,list(tv,nv),force_v4=TRUE); on.exit(ncdf4::nc_close(nc),add=TRUE); ncdf4::ncatt_put(nc,"t2m","units","K"); vals<-array(0,c(2,2,3)); for(i in 1:3) vals[,,i]<-273.15+outer(1:2,1:2,"+")+i; ncdf4::ncvar_put(nc,tv,vals); ncdf4::ncvar_put(nc,nv,1L); invisible(path)
}
test_that("NetCDF4 magic and metadata are detected", { skip_if_not_installed("ncdf4"); f<-tempfile(fileext=".nc"); make_nc4_fixture(f); expect_equal(detect_download_format(f),"netcdf4_hdf5"); md<-inspect_netcdf_ncdf4(f); expect_true(all(c("t2m","number")%in%names(md$variables))); expect_equal(select_era5_temperature_variable(md),"t2m"); expect_equal(as.character(md$decoded_dates),c("2026-07-01","2026-07-02","2026-07-03")); expect_equal(md$variables$t2m$dimensions,c("longitude","latitude","valid_time")) })
test_that("NetCDF4 reader orients, extents, and converts layers", { skip_if_not_installed("ncdf4"); f<-tempfile(fileext=".nc"); make_nc4_fixture(f); x<-read_era5_daily_with_ncdf4(f,expected_dates=as.Date("2026-07-01") + 0:2); expect_length(x$rasters,3); expect_equal(x$reader_used,"ncdf4"); expect_equal(unname(as.vector(terra::ext(x$rasters[[1]]))),c(5,25,-2,2),tolerance=1e-8); expect_equal(terra::values(x$rasters[[1]])[1],4,tolerance=1e-8); expect_equal(terra::values(x$rasters[[3]])[4],6,tolerance=1e-8) })
test_that("time decoder supports common units and rejects unsupported calendars", { expect_equal(as.character(as.Date(decode_netcdf_time(c(0,3600),"seconds since 1970-01-01 00:00:00"))),c("1970-01-01","1970-01-01")); expect_equal(as.character(as.Date(decode_netcdf_time(c(0,24),"hours since 1900-01-01 00:00:00"))),c("1900-01-01","1900-01-02")); expect_error(decode_netcdf_time(0,"days since 1970-01-01","360_day"),"Unsupported") })
test_that("NetCDF4 processing writes three masked daily outputs", { skip_if_not_installed("ncdf4"); f<-tempfile(fileext=".nc"); make_nc4_fixture(f); t<-terra::rast(nrows=2,ncols=2,xmin=5,xmax=25,ymin=-2,ymax=2,crs="EPSG:4326"); terra::values(t)<-c(1,1,NA,1); tp<-tempfile(fileext=".tif"); terra::writeRaster(t,tp,overwrite=TRUE); cfg<-list(project=list(output_prefix="mintemp"),spatial=list(mask_to_boundary=FALSE,mask_to_template=TRUE),processing=list(resampling_method="bilinear",datatype="FLT4S",naflag=-9999,delete_replaced_estimates=TRUE),validation=list(minimum_celsius=-100,maximum_celsius=70,require_exact_template_geometry=TRUE),cds=list(variable="2m_temperature")); od<-file.path(getwd(),"runtime",paste0("nc4-daily-",as.integer(Sys.time()))); x<-process_downloaded_mintemp(f,od,tp,"unused",cfg,expected_dates=as.Date("2026-07-01")+0:2); expect_length(x$written,3); expect_equal(length(list.files(od,pattern="^mintemp_.*\\.tif$")),3); expect_true(all(is.na(terra::values(terra::rast(x$written[[1]])))[3])) })
