test_that("soil moisture NetCDF aliases and units are explicit", {
  sm <- get_variable_spec("era5_soilmoist")
  md <- list(variables=list(swvl1=list(units="m^3 m^-3", dimensions=c("longitude","latitude","time"))))
  expect_equal(resolve_netcdf_variable(md, sm), "swvl1")
  md$variables <- list(volumetric_soil_water_layer_1=list(units="m3/m3", dimensions=c("longitude","latitude","time")))
  expect_equal(resolve_netcdf_variable(md, sm), "volumetric_soil_water_layer_1")
  md$variables$swvl1 <- list(units="m3/m3", dimensions=c("longitude","latitude","time"), data_signature="different")
  expect_error(resolve_netcdf_variable(md, sm), "ambiguous")
  expect_error(convert_source_units(1, sm, "percent"), "Unsupported")
})

test_that("soil moisture configurations preserve endpoint semantics", {
  config_dir <- file.path("..","..","config")
  skip_if_not(file.exists(file.path(config_dir,"era5_soilmoist_smoke.yml")), "soilmoist configs are not included in installed package checks")
  smoke <- read_pipeline_config(file.path(config_dir,"era5_soilmoist_smoke.yml"))
  weekly <- read_pipeline_config(file.path("..","..","config","era5_soilmoist_weekly_smoke.yml"))
  production <- read_pipeline_config(file.path("..","..","config","era5_soilmoist_production.yml"))
  expect_equal(unname(smoke$project$dataset_id), "era5_soilmoist")
  expect_equal(as.character(smoke$temporal$initial_start_date), "2026-07-01")
  expect_equal(as.character(weekly$temporal$initial_start_date), "2026-07-06")
  expect_equal(as.character(production$temporal$initial_start_date), "2022-01-01")
  expect_false(isTRUE(production$future$daily_enabled))
})
