test_that("variable registry resolves both covariates", {
  mt <- get_variable_spec("era5_mintemp")
  sm <- get_variable_spec("era5_soilmoist")
  expect_equal(mt$cds_variable, "2m_temperature")
  expect_equal(mt$daily_statistic, "daily_minimum")
  expect_equal(mt$weekly_statistic, "minimum")
  expect_equal(sm$cds_variable, "volumetric_soil_water_layer_1")
  expect_equal(sm$netcdf_variable_names, c("swvl1", "volumetric_soil_water_layer_1"))
  expect_equal(sm$soil_layer, list(top_cm=0, bottom_cm=7))
  expect_equal(sm$source_units, "m3 m-3")
  expect_equal(sm$unit_conversion, "identity")
  expect_equal(sm$weekly_statistic, "mean")
  expect_false(identical(mt$variable_spec_hash, sm$variable_spec_hash))
})

test_that("soil moisture values use identity conversion and physical validation", {
  sm <- get_variable_spec("era5_soilmoist")
  expect_equal(convert_source_units(c(0, .25, 1), sm), c(0, .25, 1))
  expect_equal(validate_variable_values(c(-1e-7, .5, 1+1e-7), sm)$values, c(0, .5, 1))
  expect_error(validate_variable_values(-.01, sm), "hard valid range")
  expect_error(validate_variable_values(1.01, sm), "hard valid range")
  expect_true(validate_variable_values(c(.005,.5,.9), sm)$soft_range_warning)
})
