test_that("AgERA5 ZIP fixtures extract and map one NetCDF member per date", {
  skip_if_not_installed("ncdf4")
  base <- test_external_root("agera5-archive"); src <- file.path(base,"members"); dir.create(src,recursive=TRUE)
  make_member <- function(date) {
    lon<-ncdf4::ncdim_def("lon","degrees_east",c(-126,-125.9)); lat<-ncdf4::ncdim_def("lat","degrees_north",c(42.8,42.7)); tm<-ncdf4::ncdim_def("time",paste0("days since 1900-01-01 00:00:00"),as.numeric(as.Date(date)-as.Date("1900-01-01"))); v<-ncdf4::ncvar_def("Derived_Relative_Humidity_2m_Min_24h","%",list(lon,lat,tm),-9999,prec="double"); p<-file.path(src,paste0("rh_",gsub("-","",date),".nc")); n<-ncdf4::nc_create(p,list(v),force_v4=TRUE); ncdf4::ncvar_put(n,v,array(50,dim=c(2,2,1))); ncdf4::nc_close(n); p
  }
  members <- vapply(c("2025-06-01","2025-06-02","2025-06-03"),make_member,character(1)); zip_path<-file.path(base,"response.zip"); old<-getwd(); setwd(src); on.exit(setwd(old),add=TRUE); utils::zip(zip_path,basename(members),flags="-q"); setwd(old)
  direct<-read_agera5_daily_member(members[[1]],"2025-06-01",get_variable_spec("agera5_relhum_min")); expect_equal(terra::nlyr(direct$raster),1); expect_equal(direct$selected_source_variable,"Derived_Relative_Humidity_2m_Min_24h"); expect_equal(direct$source_units,"%"); expect_equal(direct$date,"2025-06-01"); expect_true(direct$source_non_na_count>0); expect_true(direct$source_minimum>=0); expect_true(direct$source_maximum<=100)
  manifest<-extract_agera5_archive(zip_path,file.path(base,"extracted"),"fixturehash",get_variable_spec("agera5_relhum_min")); expect_equal(nrow(manifest),3); expect_true(all(manifest$detected_format%in%c("netcdf4_hdf5","netcdf_classic"))); expect_true(all(c("archive_manifest_schema_version","adapter_id","adapter_inspection_version","dataset_id","variable_spec_hash","variable_alias_hash","selection_rules_hash","created_with_package_version","selected_netcdf_variable")%in%names(manifest))); expect_true(all(manifest$selected_netcdf_variable=="Derived_Relative_Humidity_2m_Min_24h")); chosen<-select_agera5_archive_members(manifest,as.Date(c("2025-06-01","2025-06-02","2025-06-03"))); expect_equal(chosen$date_from_filename,c("2025-06-01","2025-06-02","2025-06-03")); expect_equal(length(unique(chosen$extracted_path)),3); wrapped<-read_era5_daily_layers(zip_path,variable_spec=get_variable_spec("agera5_relhum_min"),raw_request_dates=as.Date(c("2025-06-01","2025-06-02","2025-06-03")),dates_to_process=as.Date(c("2025-06-01","2025-06-02","2025-06-03")),request_hash="wrapperhash"); expect_equal(wrapped$reader_used,"terra"); expect_equal(wrapped$dates,as.Date(c("2025-06-01","2025-06-02","2025-06-03"))); expect_equal(wrapped$selected_netcdf_variable,rep("Derived_Relative_Humidity_2m_Min_24h",3)); template<-terra::rast(nrows=2,ncols=2,xmin=-126,xmax=-125.8,ymin=42.7,ymax=42.9,crs="EPSG:4326"); terra::values(template)<-1; out_dir<-file.path(base,"daily"); dir.create(out_dir); cfg<-list(validation=list(require_exact_template_geometry=TRUE,physical_minimum_percent=0,physical_maximum_percent=100),spatial=list(require_complete_template_coverage=TRUE)); for(i in seq_len(nrow(chosen))){q<-read_agera5_daily_member(chosen$extracted_path[[i]],chosen$date_from_filename[[i]],get_variable_spec("agera5_relhum_min")); z<-standardize_daily_raster(q$raster,template,boundary=NULL,resampling_method="bilinear",mask_to_boundary=FALSE,mask_to_template=TRUE); out<-file.path(out_dir,paste0("relhum_min_",q$date,".tif")); terra::writeRaster(z,out,overwrite=TRUE); expect_true(validate_raster_against_template(out,template,c(0,100),TRUE,get_variable_spec("agera5_relhum_min"))$valid); expect_equal(terra::nrow(terra::rast(out)),terra::nrow(template)); expect_equal(terra::ncol(terra::rast(out)),terra::ncol(template)); expect_true(all(terra::values(terra::rast(out),mat=FALSE)>=0,na.rm=TRUE)); expect_true(all(terra::values(terra::rast(out),mat=FALSE)<=100,na.rm=TRUE))}; expect_equal(sort(basename(list.files(out_dir,pattern="\\.tif$"))),sort(paste0("relhum_min_",c("2025-06-01","2025-06-02","2025-06-03"),".tif"))); reused<-extract_agera5_archive(zip_path,file.path(base,"extracted"),"fixturehash",get_variable_spec("agera5_relhum_min")); expect_true(isTRUE(attr(reused,"extraction_reused"))); expect_true(isTRUE(attr(reused,"manifest_reused")))
  extracted_before<-manifest$extracted_path; legacy<-manifest[,c("archive_path","archive_checksum","request_hash","member_name","member_relative_path","extracted_path","member_size","member_checksum","detected_format","date_from_filename","date_from_content","variable_candidate","selected","selection_reason","validation_message")]; legacy$variable_candidate<-FALSE; legacy$selected_netcdf_variable<-NULL; utils::write.csv(legacy,file.path(dirname(extracted_before[[1]]),"archive_manifest.csv"),row.names=FALSE)
  migrated<-extract_agera5_archive(zip_path,file.path(base,"extracted"),"fixturehash",get_variable_spec("agera5_relhum_min")); expect_true(isTRUE(attr(migrated,"extraction_reused"))); expect_false(isTRUE(attr(migrated,"manifest_reused"))); expect_equal(attr(migrated,"manifest_rebuild_reason"),"adapter fingerprint changed"); expect_equal(migrated$extracted_path,extracted_before); expect_true(all(migrated$variable_candidate)); expect_true(all(migrated$selected_netcdf_variable=="Derived_Relative_Humidity_2m_Min_24h")); expect_equal(select_agera5_archive_members(migrated,as.Date(c("2025-06-01","2025-06-02","2025-06-03")))$date_from_filename,c("2025-06-01","2025-06-02","2025-06-03"))
})

test_that("unsafe archive member names are rejected", {
  skip_if_not_installed("ncdf4")
  expect_error(archive_member_safe("../escape.nc"), NA)
  expect_false(archive_member_safe("../escape.nc"))
  expect_false(archive_member_safe("/absolute.nc"))
})
