test_that("soil moisture standardization uses bilinear projection and template mask", {
  skip_if_not_installed("terra")
  source <- terra::rast(nrows=2,ncols=2,xmin=0,xmax=2,ymin=0,ymax=2,crs="EPSG:4326")
  terra::values(source) <- c(.2,.4,.6,.8)
  template <- terra::rast(nrows=2,ncols=2,xmin=0,xmax=2,ymin=0,ymax=2,crs="EPSG:4326")
  terra::values(template) <- c(1,1,1,NA)
  out <- standardize_daily_raster(source,template,resampling_method="bilinear")
  expect_true(terra::compareGeom(out,template,stopOnError=FALSE))
  expect_true(is.na(terra::values(out)[4]))
  expect_true(validate_template_coverage(out,template,TRUE)$complete)
  expect_equal(get_variable_spec("era5_soilmoist")$spatial_interpolation, "bilinear")
})
