request_definition_hash <- function(dates, cds_area, config, buffer_degrees=NULL, align_to_source_grid=NULL) {
  digest::digest(list(dates=as.character(sort(unique(as.Date(dates)))), dataset=config$cds$dataset_short_name, variable=config$cds$variable, daily_statistic=config$cds$daily_statistic, frequency=config$cds$frequency, area=as.numeric(cds_area), source_grid_alignment=isTRUE(align_to_source_grid), buffer_degrees=buffer_degrees), algo="xxhash32")
}
build_variable_requests <- function(planned_dates, cds_area, config, variable_spec=NULL) {
  spec <- variable_spec %||% get_variable_spec(config$project$dataset_id, config); d <- sort(unique(as.Date(planned_dates))); if(!length(d)) return(list()); if(length(cds_area)!=4 || cds_area[1]<=cds_area[3] || cds_area[2]>=cds_area[4]) stop("CDS area must be north, west, south, east"); g <- split(d, format(d,"%Y-%m")); lapply(g, function(x) { ym <- format(x[1],"%Y-%m"); h <- request_definition_hash(x,cds_area,config,config$spatial$api_bbox_buffer_degrees %||% NULL,config$spatial$align_request_to_source_grid %||% FALSE); target <- sprintf("%s_daily_%s-%s_%s.nc", spec$id, substr(ym,1,4),substr(ym,6,7),substr(h,1,8)); list(dataset_short_name=spec$dataset_short_name, product_type=config$cds$product_type, variable=spec$cds_variable, year=substr(ym,1,4), month=substr(ym,6,7), day=format(x,"%d"), daily_statistic=spec$daily_statistic, time_zone=spec$time_zone, frequency=spec$frequency, data_format=config$cds$data_format, download_format=config$cds$download_format, area=as.numeric(cds_area), source_grid_alignment=isTRUE(config$spatial$align_request_to_source_grid), buffer_degrees=config$spatial$api_bbox_buffer_degrees %||% NULL, request_hash=h, variable_spec_hash=spec$variable_spec_hash, target=target) })
}
build_era5_mintemp_requests <- function(planned_dates, cds_area, config) build_variable_requests(planned_dates, cds_area, config, get_variable_spec("era5_mintemp", config))
validate_cds_request_structure <- function(request) { stopifnot(is.list(request)); required <- c("dataset_short_name","product_type","variable","year","month","day","daily_statistic","time_zone","frequency","data_format","download_format","area","target"); if(!all(required %in% names(request))) stop("Missing CDS request fields"); spec <- get_variable_spec(request$variable); if(request$dataset_short_name!=spec$dataset_short_name||request$variable!=spec$cds_variable||request$daily_statistic!=spec$daily_statistic) stop("Invalid ERA5 request specification"); if(!grepl("^\\d{4}$",request$year)||!grepl("^\\d{2}$",request$month)||any(!grepl("^\\d{2}$",request$day))||any(as.integer(request$day)<1|as.integer(request$day)>31)) stop("Invalid request date fields"); if(length(request$area)!=4||request$area[1]<=request$area[3]||request$area[2]>=request$area[4]) stop("Invalid area"); if("user" %in% names(request)||request$data_format!="netcdf"||request$download_format!="unarchived") stop("Invalid or unsafe CDS request fields"); TRUE }
cds_api_fields <- c("product_type","variable","year","month","day","daily_statistic","time_zone","frequency","data_format","download_format","area")
cds_internal_fields <- c("source_grid_alignment","buffer_degrees","source_grid_degrees","request_extent_source","request_hash","target","target_filename","resolved_target_path","planned_dates")
validate_cds_api_payload <- function(payload) {
  if(!is.list(payload)) stop("CDS API payload must be a list",call.=FALSE); unexpected <- setdiff(names(payload),cds_api_fields); if(length(unexpected)) stop("Unexpected fields in CDS API payload: ",paste(unexpected,collapse=", "),call.=FALSE); missing <- setdiff(cds_api_fields,names(payload)); if(length(missing)) stop("CDS API payload is missing required fields: ",paste(missing,collapse=", "),call.=FALSE)
  char_fields <- setdiff(cds_api_fields,c("day","area")); if(any(!vapply(payload[char_fields],function(x)is.character(x)&&length(x)>=1L,logical(1)))) stop("CDS API character fields must be character values",call.=FALSE); if(!is.character(payload$day)||!length(payload$day)) stop("CDS API day must be a character vector",call.=FALSE); if(!is.numeric(payload$area)||length(payload$area)!=4L||payload$area[1]<=payload$area[3]||payload$area[4]<=payload$area[2]) stop("CDS API area must be north, west, south, east",call.=FALSE); if(any(cds_internal_fields %in% names(payload))) stop("Internal pipeline metadata must not be sent to CDS",call.=FALSE); TRUE
}
build_cds_api_payload <- function(request_record) { missing <- setdiff(cds_api_fields,names(request_record)); if(length(missing)) stop("Request record is missing required CDS fields: ",paste(missing,collapse=", "),call.=FALSE); payload <- request_record[cds_api_fields]; validate_cds_api_payload(payload); payload }
write_cds_request_manifests <- function(requests, run_dir) { fs::dir_create(run_dir,recurse=TRUE); rows <- if(length(requests)) do.call(rbind,lapply(requests,function(x) data.frame(year=x$year,month=x$month,days=paste(x$day,collapse=","),area=paste(x$area,collapse=","),target=x$target,stringsAsFactors=FALSE))) else data.frame(); utils::write.csv(rows,file.path(run_dir,"request_manifest.csv"),row.names=FALSE); jsonlite::write_json(requests,file.path(run_dir,"request_manifest.json"),pretty=TRUE,auto_unbox=TRUE); invisible(rows) }
