extract_daily_layers <- function(nc_file, expected_variable="2m_temperature", variable_spec=NULL) read_era5_daily_layers(nc_file, variable_spec=variable_spec %||% get_variable_spec(expected_variable))
standardize_daily_raster <- function(source,template,boundary=NULL,resampling_method="bilinear",mask_to_boundary=FALSE,mask_to_template=TRUE) { if(!requireNamespace("terra",quietly=TRUE))stop("terra is required");out<-terra::project(source,template,method=resampling_method);if(mask_to_template)out<-terra::mask(out,template);if(mask_to_boundary&&!is.null(boundary))out<-terra::mask(out,terra::vect(boundary));out }
process_downloaded_variable <- function(raw_files,daily_dir,template_path,bbox_path,config,variable_spec=NULL,overwrite_dates=NULL,expected_dates=NULL,run_dir=NULL) {
  spec<-variable_spec%||%get_variable_spec(config$project$dataset_id,config);fs::dir_create(daily_dir,recurse=TRUE);template<-terra::rast(template_path);before<-template_fingerprint(template);boundary<-if(isTRUE(config$spatial$mask_to_boundary))sf::st_read(bbox_path,quiet=TRUE)else NULL;written<-reused<-replaced<-failed<-character();readers<-list();
  if(!length(raw_files)&&!is.null(expected_dates)){existing_inv<-inventory_daily_products(daily_dir,spec$daily_filename_prefix,template_path,TRUE,config);reused<-existing_inv$path[existing_inv$observed_valid%in%TRUE&existing_inv$date%in%as.Date(expected_dates)]}
  for(f in raw_files){x<-tryCatch(read_era5_daily_layers(f,expected_dates=expected_dates,variable_spec=spec),error=function(e){failed<<-c(f,failed);NULL});if(is.null(x))next;readers[[f]]<-list(reader_used=x$reader_used,source_format=x$source_format,selected_variable=x$selected_variable%||%NA,selected_variable_alias=x$selected_variable_alias%||%NA,source_units=x$source_units%||%NA,dates=x$dates,dimension_names=x$dimension_names%||%character(),dimension_order=x$dimension_order%||%character(),daily_statistic_source=x$daily_statistic_source%||%"cds_daily_statistics",daily_statistic=x$daily_statistic%||%"mean",subdaily_frequency=x$subdaily_frequency%||%spec$frequency)
    for(i in seq_along(x$dates)){d<-x$dates[i];if(!is.null(expected_dates)&&!(d%in%as.Date(expected_dates)))next;out<-file.path(daily_dir,daily_output_filename(spec,d));existed_before<-file.exists(out);valid_before<-FALSE;if(existed_before){vr0<-validate_daily_output(out,d,template,config,variable_spec=spec);valid_before<-isTRUE(vr0$valid);if(valid_before&&is.null(overwrite_dates)){if(!out%in%reused)reused<-c(reused,out);next}};if(!is.null(overwrite_dates)&&!(d%in%as.Date(overwrite_dates)))next;z<-standardize_daily_raster(x$rasters[[i]],template,boundary,config$processing$resampling_method,isTRUE(config$spatial$mask_to_boundary),isTRUE(config$spatial$mask_to_template));stats<-validate_variable_values(terra::values(z,mat=FALSE),spec,config$validation$hard_tolerance%||%1e-6);terra::values(z)<-stats$values;vr<-validate_raster_against_template(z,template,spec$hard_valid_range,TRUE,variable_spec=spec);coverage<-tryCatch(validate_template_coverage(z,template,isTRUE(config$spatial$require_complete_template_coverage%||%TRUE),if(isTRUE(config$spatial$write_coverage_diagnostics)&&!is.null(run_dir))file.path(run_dir,"diagnostics","coverage")else NULL,d),error=function(e)e);if(!vr$valid||inherits(coverage,"error")){failed<-c(failed,out);next};tmp<-paste0(out,".tmp.tif");terra::writeRaster(z,tmp,overwrite=TRUE,wopt=list(datatype=config$processing$datatype,gdal=c("COMPRESS=DEFLATE","PREDICTOR=3","TILED=YES"),NAflag=config$processing$naflag));if(file.exists(out))unlink(out);if(!file.rename(tmp,out))stop("Could not promote daily output: ",out,call.=FALSE);sidecar<-paste0(out,".json");meta<-c(list(variable_id=spec$id,short_name=spec$short_name,long_name=spec$long_name,soil_layer_top_cm=spec$soil_layer$top_cm%||%NULL,soil_layer_bottom_cm=spec$soil_layer$bottom_cm%||%NULL,source_units=readers[[f]]$source_units,output_units=spec$output_units,daily_statistic="mean",weekly_statistic=spec$weekly_statistic,spatial_interpolation=spec$spatial_interpolation,variable_spec_hash=spec$variable_spec_hash,template_sha256=template_fingerprint(template)$sha256,daily_statistic_source="cds_daily_statistics",soft_range_warning=stats$soft_range_warning),stats);jsonlite::write_json(meta,sidecar,auto_unbox=TRUE,pretty=TRUE,null="null");if(existed_before&&!valid_before)replaced<-c(replaced,out)else written<-c(written,out)}}
  if(!identical(before,template_fingerprint(template)))stop("Template fingerprint changed during processing");stopifnot(!length(intersect(written,reused)),!length(intersect(written,replaced)),!length(intersect(reused,replaced)));list(written=written,reused=reused,replaced=replaced,failed=failed,readers=readers,variable_spec_hash=spec$variable_spec_hash)
}
process_downloaded_mintemp <- function(raw_files,daily_dir,template_path,bbox_path,config,overwrite_dates=NULL,expected_dates=NULL,run_dir=NULL) process_downloaded_variable(raw_files,daily_dir,template_path,bbox_path,config,get_variable_spec("era5_mintemp",config),overwrite_dates,expected_dates,run_dir)
