extract_daily_layers <- function(nc_file, expected_variable="2m_temperature", variable_spec=NULL) read_era5_daily_layers(nc_file, variable_spec=variable_spec %||% get_variable_spec(expected_variable))
standardize_daily_raster <- function(source,template,boundary=NULL,resampling_method="bilinear",mask_to_boundary=FALSE,mask_to_template=TRUE) { if(!requireNamespace("terra",quietly=TRUE))stop("terra is required"); out<-terra::project(source,template,method=resampling_method); if(mask_to_template)out<-terra::mask(out,template); if(mask_to_boundary&&!is.null(boundary))out<-terra::mask(out,terra::vect(boundary)); out }
process_downloaded_variable <- function(raw_files,daily_dir,template_path,bbox_path,config,variable_spec=NULL,overwrite_dates=NULL,expected_dates=NULL,run_dir=NULL,run_expected_dates=NULL,request_manifest=NULL,date_source_map=NULL) {
  spec <- variable_spec %||% get_variable_spec(config$project$dataset_id,config); run_expected_dates <- normalize_date_vector(run_expected_dates %||% expected_dates,"run_expected_dates"); if(!is.null(request_manifest)&&!is.null(date_source_map))validate_date_source_map(date_source_map,raw_files,request_manifest); fs::dir_create(daily_dir,recurse=TRUE); template<-terra::rast(template_path); before<-template_fingerprint(template); boundary<-if(isTRUE(config$spatial$mask_to_boundary))sf::st_read(bbox_path,quiet=TRUE)else NULL; written<-reused<-replaced<-failed<-character(); readers<-list(); processing_failures<-list()
  add_failure <- function(raw_path,date=NA,step,e,metadata=list()) { z<-list(raw_path=raw_path,date=if(is.na(date))NA_character_ else format(as.Date(date),"%Y-%m-%d"),variable_id=spec$id,selected_netcdf_variable=metadata$selected_variable %||% spec$netcdf_variable_names[[1]],source_units=metadata$source_units_original %||% metadata$source_units %||% spec$source_units,processing_step=step,error_class=class(e)[1],error_message=conditionMessage(e),warnings=metadata$warnings %||% character()); processing_failures[[length(processing_failures)+1L]]<<-z; failed<<-c(failed,if(is.na(date))raw_path else file.path(daily_dir,daily_output_filename(spec,date))) }
  if(!length(raw_files)&&length(run_expected_dates)){existing_inv<-inventory_daily_products(daily_dir,spec$daily_filename_prefix,template_path,TRUE,config);reused<-existing_inv$path[existing_inv$observed_valid%in%TRUE&existing_inv$date%in%run_expected_dates]}
  for(f in raw_files) {
    req <- if(!is.null(request_manifest))request_entry_for_raw(f,request_manifest)else NULL; raw_request_dates <- if(!is.null(req))build_request_dates(req)else run_expected_dates; dates_to_process <- if(!is.null(date_source_map))selected_dates_for_raw(f,date_source_map)else raw_request_dates; if(!length(dates_to_process))next
    x <- tryCatch(read_era5_daily_layers(f,variable_spec=spec,raw_request_dates=raw_request_dates,dates_to_process=dates_to_process,request_hash=req$request_hash %||% NULL),error=function(e){add_failure(f,NA,"netcdf_read",e);NULL}); if(is.null(x))next
    readers[[f]] <- list(reader_used=x$reader_used,source_format=x$source_format,selected_variable=x$selected_variable %||% NA,selected_netcdf_variable=x$selected_netcdf_variable %||% x$selected_variable %||% NA,selected_variable_alias=x$selected_variable_alias %||% NA,data_variable_dimensions=x$data_variable_dimensions %||% x$dimension_names %||% character(),source_units=x$source_units %||% NA,source_units_original=x$source_units_original %||% x$source_units %||% NA,source_units_normalized=x$source_units_normalized %||% NA,output_units=x$output_units %||% spec$output_units,unit_conversion=x$unit_conversion %||% spec$unit_conversion,source_value_minimum=x$source_value_minimum %||% NA_real_,source_value_maximum=x$source_value_maximum %||% NA_real_,raw_request_dates=raw_request_dates,raw_request_hash=req$request_hash %||% NA_character_,raw_checksum=if(file.exists(f))digest::digest(file=f,algo="sha256") else NA_character_,dates_to_process=dates_to_process,dates=x$dates,dimension_names=x$dimension_names %||% character(),dimension_lengths=x$dimension_lengths %||% numeric(),dimension_order=x$dimension_order %||% character(),decoded_dates=x$decoded_dates %||% x$dates,latitude_direction=x$latitude_direction %||% NA,longitude_direction=x$longitude_direction %||% NA,longitude_convention=x$longitude_convention %||% NA,time_coordinate_name=x$time_coordinate_name %||% NA,time_coordinate_units=x$time_coordinate_units %||% NA,time_coordinate_raw_values=x$time_coordinate_raw_values %||% numeric(),time_coordinate_calendar_effective=x$time_coordinate_calendar_effective %||% "standard",daily_statistic_source=x$daily_statistic_source %||% "cds_daily_statistics",daily_statistic=x$daily_statistic %||% spec$daily_statistic,subdaily_frequency=x$subdaily_frequency %||% spec$frequency)
    for(i in seq_along(x$dates)) { d<-x$dates[i]; out<-file.path(daily_dir,daily_output_filename(spec,d)); existed_before<-file.exists(out); valid_before<-FALSE; if(existed_before){vr0<-validate_daily_output(out,d,template,config,variable_spec=spec);valid_before<-isTRUE(vr0$valid);if(valid_before&&is.null(overwrite_dates)){if(!out%in%reused)reused<-c(reused,out);next}};if(!is.null(overwrite_dates)&&!(d%in%as.Date(overwrite_dates)))next
      tryCatch({z<-standardize_daily_raster(x$rasters[[i]],template,boundary,config$processing$resampling_method,isTRUE(config$spatial$mask_to_boundary),isTRUE(config$spatial$mask_to_template));stats<-if(spec$id%in%c("era5_soilmoist","era5_lai_low","agera5_relhum_min"))normalize_output_values(terra::values(z,mat=FALSE),spec,config)else validate_variable_values(terra::values(z,mat=FALSE),spec,config$validation$hard_tolerance %||% 1e-6);terra::values(z)<-stats$values;vr<-validate_raster_against_template(z,template,spec$hard_valid_range,TRUE,variable_spec=spec);coverage<-validate_template_coverage(z,template,isTRUE(config$spatial$require_complete_template_coverage %||% TRUE),if(isTRUE(config$spatial$write_coverage_diagnostics)&&!is.null(run_dir))file.path(run_dir,"diagnostics","coverage")else NULL,d,spec$daily_filename_prefix);if(!vr$valid)stop(vr$message,call.=FALSE);tmp<-paste0(out,".tmp.tif");terra::writeRaster(z,tmp,overwrite=TRUE,wopt=list(datatype=config$processing$datatype,gdal=c("COMPRESS=DEFLATE","PREDICTOR=3","TILED=YES"),NAflag=config$processing$naflag));if(!file.exists(tmp))stop("Temporary raster was not created",call.=FALSE);check<-validate_raster_against_template(tmp,template,spec$hard_valid_range,TRUE,spec);if(!check$valid)stop(paste0("Temporary raster validation failed: ",check$message),call.=FALSE);if(file.exists(out))unlink(out);if(!file.rename(tmp,out))stop("Could not atomically promote daily output: ",out,call.=FALSE);sidecar<-paste0(out,".json");meta<-c(list(variable_id=spec$id,short_name=spec$short_name,long_name=spec$long_name,model_alias=spec$model_alias%||%NULL,source_dataset=spec$dataset_short_name,source_variable=spec$cds_variable,netcdf_alias=readers[[f]]$selected_variable_alias,source_units=readers[[f]]$source_units,source_units_original=readers[[f]]$source_units_original,source_units_normalized=readers[[f]]$source_units_normalized,output_units=spec$output_units,unit_conversion=spec$unit_conversion,daily_statistic=spec$daily_statistic,weekly_statistic=spec$weekly_statistic,spatial_interpolation=spec$spatial_interpolation,variable_spec_hash=spec$variable_spec_hash,template_sha256=template_fingerprint(template)$sha256,daily_statistic_source=x$daily_statistic_source%||%"cds_daily_statistics",source_minimum=readers[[f]]$source_value_minimum,source_maximum=readers[[f]]$source_value_maximum,temporal_character=spec$temporal_character%||%NULL,interannual_variability=spec$interannual_variability%||%NULL,daily_time_basis=spec$daily_time_basis%||%spec$time_zone,source_grid_degrees=spec$source_grid_degrees%||%NULL,spatial_processing=spec$spatial_processing%||%NULL,soft_range_warning=stats$soft_range_warning),stats);jsonlite::write_json(meta,sidecar,auto_unbox=TRUE,pretty=TRUE,null="null");if(existed_before&&!valid_before)replaced<-c(replaced,out)else written<-c(written,out)},error=function(e)add_failure(f,d,"daily_output",e,readers[[f]]))
    }
  }
  if(!identical(before,template_fingerprint(template)))stop("Template fingerprint changed during processing");stopifnot(!length(intersect(written,reused)),!length(intersect(written,replaced)),!length(intersect(reused,replaced)));list(written=written,reused=reused,replaced=replaced,failed=failed,processing_failures=processing_failures,readers=readers,variable_spec_hash=spec$variable_spec_hash)
}
process_downloaded_mintemp <- function(raw_files,daily_dir,template_path,bbox_path,config,overwrite_dates=NULL,expected_dates=NULL,run_dir=NULL) process_downloaded_variable(raw_files,daily_dir,template_path,bbox_path,config,get_variable_spec("era5_mintemp",config),overwrite_dates,expected_dates,run_dir)
