run_era5_mintemp_pipeline <- function(config_path="config/era5_mintemp.yml",mode=c("diagnose","plan","download","process","aggregate","estimate","full"),dry_run=TRUE,observed_end=NULL,future_end=NULL,output_root=NULL,overwrite=FALSE,rebuild_all_weeks=FALSE,execution_source="default",transfer_fun=NULL) {
  mode <- match.arg(mode); m <- NULL
  tryCatch({
    root <- resolve_project_root(dirname(config_path)); cfg <- read_pipeline_config(config_path); cfg <- resolve_config_paths(cfg,root,output_root,FALSE); if(!is.null(observed_end)) cfg$temporal$observed_end <- as.Date(observed_end); if(!is.null(future_end)) cfg$temporal$future_end_date <- as.Date(future_end); cfg <- validate_pipeline_config(cfg); storage <- resolve_storage_paths(cfg,root,output_root,create=TRUE); cfg$project_root <- root; m <- initialize_run_manifest(cfg,mode,dry_run,execution_source); log_stage(storage,m$run_id,"initialization","success")
    invd <- inventory_daily_products(storage$daily_dir,cfg$project$output_prefix,cfg$spatial$template_path,TRUE,cfg); invw <- inventory_grid_directory(storage$weekly_dir,cfg$project$output_prefix,"weekly",TRUE); diag <- diagnose_spatial_domain(cfg$spatial$template_path,cfg$spatial$bbox_path,cfg); area <- diag$final_cds_area
    if(mode %in% c("diagnose","plan","full","download")) {
      m <- update_manifest_stage(m,"plan","running"); log_stage(storage,m$run_id,"plan","start"); plan <- plan_observed_update(invd,cfg$temporal$initial_start_date,cfg$temporal$observed_end,cfg$temporal$overlap_days); qplan <- quarantine_invalid_daily_outputs(invd,storage,m$run_id,dry_run=TRUE); req <- build_era5_mintemp_requests(plan$date,area,cfg); write_cds_request_manifests(req,m$run_dir); utils::write.csv(plan,file.path(m$run_dir,"planned_dates.csv"),row.names=FALSE); utils::write.csv(compress_dates_to_intervals(plan$date),file.path(m$run_dir,"planned_intervals.csv"),row.names=FALSE); utils::write.csv(invd,file.path(m$run_dir,"inventory_daily.csv"),row.names=FALSE); utils::write.csv(invw,file.path(m$run_dir,"inventory_weekly.csv"),row.names=FALSE); utils::write.csv(qplan,file.path(m$run_dir,"planned_quarantine.csv"),row.names=FALSE); jsonlite::write_json(diag,file.path(m$run_dir,"spatial_diagnostics.json"),pretty=TRUE,auto_unbox=TRUE); m$spatial_diagnostics <- diag; m$request_area_hash <- if(length(req)) req[[1]]$request_hash else NA_character_; m$daily_products_invalid <- sum(!invd$observed_valid & invd$filename_valid,na.rm=TRUE); m$daily_products_valid <- sum(invd$observed_valid,na.rm=TRUE); m$daily_products_quarantine_planned <- nrow(qplan); m <- update_manifest_stage(m,"plan","success",list(planned_dates=as.character(plan$date))); log_stage(storage,m$run_id,"plan","success",c(sprintf("planned_dates=%d",nrow(plan))))
      if(mode %in% c("download","full") && !dry_run) {
        m <- update_manifest_stage(m,"download","running"); log_stage(storage,m$run_id,"download","start",c(paste0("request_hash=",m$request_area_hash),paste0("target_filename=",if(length(req)) req[[1]]$target else "none"),paste0("resolved_target_path=",if(length(req)) resolve_download_target(req[[1]],storage) else "none"),paste0("request_area=",paste(area,collapse=",")))); qexec <- quarantine_invalid_daily_outputs(invd,storage,m$run_id,dry_run=FALSE); m$daily_products_quarantined <- nrow(qexec); dl <- download_cds_requests(req,run_dir=m$run_dir,dry_run=FALSE,overwrite=overwrite,workers=cfg$cds$batch_workers,paths=storage,config=cfg,run_id=m$run_id,transfer_fun=transfer_fun); m$download_result <- dl; m <- update_manifest_stage(m,"download","success",list(result=dl)); log_stage(storage,m$run_id,"download","success",c("download_target_exists=TRUE",paste0("download_target_size=",if(nrow(dl)) dl$size[[1]] else NA),paste0("download_target_format=",if(nrow(dl)) dl$format[[1]] else NA),"download_target_readable=TRUE"))
      } else if(mode %in% c("download","full")) { m <- update_manifest_stage(m,"download","not_run"); log_stage(storage,m$run_id,"download","not_run") }
    } else plan <- data.frame()
    if(mode %in% c("process","full") && !dry_run) { m <- update_manifest_stage(m,"process","running"); log_stage(storage,m$run_id,"process","start"); raw_all <- if(dir.exists(storage$raw_dir)) list.files(storage$raw_dir,full.names=TRUE) else character(); raw_ok <- raw_all[vapply(raw_all,function(z) detect_download_format(z) %in% c("netcdf4_hdf5","netcdf_classic","zip","grib"),logical(1))]; expected <- seq(cfg$temporal$initial_start_date,cfg$temporal$observed_end,by="day"); pr <- process_downloaded_mintemp(raw_ok,storage$daily_dir,cfg$spatial$template_path,cfg$spatial$bbox_path,cfg,overwrite_dates=if(overwrite) expected else NULL,expected_dates=expected,run_dir=m$run_dir); m$daily_outputs_written <- length(pr$written); m$daily_outputs_reused <- length(pr$reused); m$daily_outputs_failed <- length(pr$failed); m$netcdf_readers <- pr$readers; if(length(pr$written)+length(pr$reused)==0) stop("pipeline_status=failed\nfailed_stage=process\nNo validated daily outputs were written or reused",call.=FALSE); if(length(pr$failed)) stop("pipeline_status=failed\nfailed_stage=process\nDaily processing errors occurred",call.=FALSE); m <- update_manifest_stage(m,"process","success",list(result=pr)); log_stage(storage,m$run_id,"process","success") } else if(mode %in% c("process","full")) { m <- update_manifest_stage(m,"process","not_run"); log_stage(storage,m$run_id,"process","not_run") }
    if(mode %in% c("aggregate","full") && !dry_run) { m <- update_manifest_stage(m,"aggregate","running"); aggregate_daily_to_weekly(storage$daily_dir,storage$weekly_dir,cfg$project$output_prefix,overwrite=TRUE,template_path=cfg$spatial$template_path,rebuild_all=rebuild_all_weeks); m <- update_manifest_stage(m,"aggregate","success"); log_stage(storage,m$run_id,"aggregate","success") } else if(mode %in% c("aggregate","full")) m <- update_manifest_stage(m,"aggregate","not_run")
    for(stage in c("plan","download","process","aggregate","estimate","final_validation")) if(!stage %in% m$completed_stages && !stage %in% names(m$stage_results)) m <- update_manifest_stage(m,stage,"not_run")
    finalize_run_manifest(m,"success")
  }, error=function(e) { if(!is.null(m)) { msg <- conditionMessage(e); failed <- if(grepl("failed_stage=",msg)) sub(".*failed_stage=([^[:space:]]+).*","\\1",msg) else if(identical(m$current_stage,"download")) "download" else m$current_stage; m$pipeline_status <- "failed"; m$failed_stage <- failed; m$failure_class <- class(e); m$failure_message <- msg; m$current_stage <- failed; m$stage_results[[failed]] <- list(status="failed",failure_message=msg); for(stage in c("plan","download","process","aggregate","estimate","final_validation")) if(is.null(m$stage_results[[stage]])) m$stage_results[[stage]] <- list(status="not_run"); m <- finalize_run_manifest(m,"failed"); log_stage(m$storage_paths,m$run_id,failed,"failed",paste0("failure_reason=",gsub("\\n"," ",msg))) }; stop(e) })
}
