final_validate_smoke_run <- function(inventory, expected_dates, weekly_result, template_path) {
  expected <- sort(unique(as.Date(expected_dates))); valid <- inventory$observed_valid %in% TRUE; dates <- sort(unique(inventory$date[valid & !inventory$estimated])); invalid <- inventory[!valid & !inventory$estimated,,drop=FALSE]; missing <- setdiff(expected,dates); duplicates <- dates[duplicated(dates)]; if(length(missing)||nrow(invalid)||length(duplicates)) stop("Final validation failed: daily coverage is incomplete or invalid",call.=FALSE); list(status="success",expected_observed_dates=length(expected),valid_observed_daily_products=sum(valid & !inventory$estimated),invalid_daily_products=nrow(invalid),missing_expected_dates=as.character(missing),duplicate_observed_dates=length(duplicates),weekly_outputs_written=length(weekly_result$written %||% character()),incomplete_weeks=nrow(weekly_result$incomplete_weeks %||% data.frame()))
}

run_era5_mintemp_pipeline <- function(config_path="config/era5_mintemp.yml",mode=c("diagnose","plan","download","process","aggregate","estimate","full"),dry_run=TRUE,observed_end=NULL,future_end=NULL,output_root=NULL,overwrite=FALSE,rebuild_all_weeks=FALSE,execution_source="default",transfer_fun=NULL) {
  mode <- match.arg(mode); m <- NULL
  tryCatch({
    root<-resolve_project_root(dirname(config_path)); cfg<-read_pipeline_config(config_path); cfg<-resolve_config_paths(cfg,root,output_root,FALSE); if(!is.null(observed_end))cfg$temporal$observed_end<-as.Date(observed_end); if(!is.null(future_end))cfg$temporal$future_end_date<-as.Date(future_end); cfg<-validate_pipeline_config(cfg); storage<-resolve_storage_paths(cfg,root,output_root,create=TRUE); cfg$project_root<-root; m<-initialize_run_manifest(cfg,mode,dry_run,execution_source); log_stage(storage,m$run_id,"initialization","success")
    template<-terra::rast(cfg$spatial$template_path); inv_before<-inventory_daily_products(storage$daily_dir,cfg$project$output_prefix,cfg$spatial$template_path,TRUE,cfg); invw<-inventory_grid_directory(storage$weekly_dir,cfg$project$output_prefix,"weekly",TRUE); diag<-diagnose_spatial_domain(cfg$spatial$template_path,cfg$spatial$bbox_path,cfg); area<-diag$final_cds_area; expected<-seq(cfg$temporal$initial_start_date,cfg$temporal$observed_end,by="day"); req<-list(); dl<-data.frame()
    if(mode %in% c("diagnose","plan","download","full")){ m<-update_manifest_stage(m,"plan","running"); plan<-plan_observed_update(inv_before,cfg$temporal$initial_start_date,cfg$temporal$observed_end,cfg$temporal$overlap_days); req<-if(nrow(plan))build_era5_mintemp_requests(plan$date,area,cfg)else list(); write_cds_request_manifests(req,m$run_dir); utils::write.csv(plan,file.path(m$run_dir,"planned_dates.csv"),row.names=FALSE); utils::write.csv(inv_before,file.path(m$run_dir,"inventory_daily_before_process.csv"),row.names=FALSE); jsonlite::write_json(diag,file.path(m$run_dir,"spatial_diagnostics.json"),pretty=TRUE,auto_unbox=TRUE); m$spatial_diagnostics<-diag; m$request_area_hash<-if(length(req))req[[1]]$request_hash else NA_character_; m<-update_manifest_stage(m,if(identical(attr(plan,"status"),"success_noop"))"plan" else "plan","success_noop"%in%c(attr(plan,"status"))%||%"success",list(status=attr(plan,"status"),reason=attr(plan,"reason"),planned_dates=as.character(plan$date))); log_stage(storage,m$run_id,"plan","success",c(sprintf("configured_observed_start=%s",cfg$temporal$initial_start_date),sprintf("configured_observed_end=%s",cfg$temporal$observed_end),sprintf("latest_valid_observed_date=%s",if(length(inv_before$date[inv_before$observed_valid%in%TRUE]))max(inv_before$date[inv_before$observed_valid%in%TRUE])else NA),sprintf("candidate_start=%s",cfg$temporal$initial_start_date),sprintf("candidate_end=%s",cfg$temporal$observed_end),sprintf("valid_observed_date_count=%d",sum(inv_before$observed_valid%in%TRUE)),sprintf("planned_date_count=%d",nrow(plan)),paste0("reason=",attr(plan,"reason")))) }
    if(mode %in% c("download","full")&&!dry_run){ if(!length(req)){m<-update_manifest_stage(m,"download","success_noop",list(reason="no_requests"));log_stage(storage,m$run_id,"download","success_noop","reason=no_requests")}else{m<-update_manifest_stage(m,"download","running");log_stage(storage,m$run_id,"download","start",c(paste0("request_hash=",req[[1]]$request_hash),paste0("target_filename=",req[[1]]$target)));dl<-download_cds_requests(req,run_dir=m$run_dir,dry_run=FALSE,overwrite=overwrite,paths=storage,config=cfg,run_id=m$run_id,transfer_fun=transfer_fun);m$download_result<-dl;m<-update_manifest_stage(m,"download","success",list(result=dl));log_stage(storage,m$run_id,"download","success")} } else if(mode %in% c("download","full")){m<-update_manifest_stage(m,"download","not_run")}
    raw_all<-if(dir.exists(storage$raw_dir))list.files(storage$raw_dir,full.names=TRUE,pattern="\\.(nc|nc4|zip|grib)$",ignore.case=TRUE)else character(); active_req<-if(length(req))req else build_era5_mintemp_requests(expected,area,cfg); sel<-select_active_raw_inputs(active_req,dl,raw_all); m$active_raw_inputs<-sel$active; m$reused_matching_raw_inputs<-sel$reused_matching; m$unmatched_raw_inputs<-sel$unmatched; m$superseded_raw_inputs<-sel$superseded; m$invalid_raw_inputs<-sel$invalid; m$date_source_map<-map_dates_to_active_raw_sources(sel$active,active_req)
    if(mode %in% c("process","full")&&!dry_run){m<-update_manifest_stage(m,"process","running"); log_stage(storage,m$run_id,"process","start",paste0("active_raw_inputs=",length(sel$active))); pr<-process_downloaded_mintemp(sel$active,storage$daily_dir,cfg$spatial$template_path,cfg$spatial$bbox_path,cfg,overwrite_dates=if(overwrite)expected else NULL,expected_dates=expected,run_dir=m$run_dir); m$daily_outputs_written<-length(pr$written);m$daily_outputs_reused<-length(pr$reused);m$daily_outputs_replaced<-length(pr$replaced);m$daily_outputs_failed<-length(pr$failed);m$daily_inventory_before_process<-inv_before; if(!length(pr$written)&&!length(pr$reused)&&!length(pr$replaced)&&!nrow(inv_before))stop("pipeline_status=failed\nfailed_stage=process\nNo validated daily outputs were written or reused",call.=FALSE); m<-update_manifest_stage(m,"process","success",list(result=pr)); log_stage(storage,m$run_id,"process","success") } else if(mode %in% c("process","full")){m<-update_manifest_stage(m,"process","not_run")}
    inv_after<-inventory_daily_products(storage$daily_dir,cfg$project$output_prefix,cfg$spatial$template_path,TRUE,cfg); m$daily_inventory_after_process<-inv_after; m$daily_products_valid<-sum(inv_after$observed_valid,na.rm=TRUE);m$daily_products_invalid<-sum(!inv_after$observed_valid & !inv_after$estimated,na.rm=TRUE);m$valid_observed_dates<-as.character(sort(unique(inv_after$date[inv_after$observed_valid & !inv_after$estimated])));m$invalid_observed_dates<-as.character(sort(unique(inv_after$date[!inv_after$observed_valid & !inv_after$estimated])))
    weekly_result<-list(status="success_noop",written=character(),reused=character(),incomplete_weeks=data.frame()); if(mode %in% c("aggregate","full")&&!dry_run){m<-update_manifest_stage(m,"aggregate","running"); weekly_result<-aggregate_daily_to_weekly(storage$daily_dir,storage$weekly_dir,cfg$project$output_prefix,overwrite=TRUE,template_path=cfg$spatial$template_path,rebuild_all=rebuild_all_weeks,inventory=inv_after);m$affected_iso_weeks<-weekly_result$incomplete_weeks$week_id %||% character();m$incomplete_iso_weeks<-weekly_result$incomplete_weeks$week_id %||% character();m$complete_iso_weeks<-weekly_result$complete_weeks %||% character();m$weekly_outputs_written<-length(weekly_result$written);m$weekly_outputs_reused<-length(weekly_result$reused);m<-update_manifest_stage(m,"aggregate",weekly_result$status,list(result=weekly_result));log_stage(storage,m$run_id,"aggregate",weekly_result$status,c(paste0("valid_daily_products=",m$daily_products_valid),paste0("affected_iso_weeks=",length(m$affected_iso_weeks)),paste0("weekly_outputs_written=",m$weekly_outputs_written))) } else if(mode %in% c("aggregate","full")){m<-update_manifest_stage(m,"aggregate","not_run")}
    m<-update_manifest_stage(m,"estimate",if(isTRUE(cfg$future$daily_enabled)||isTRUE(cfg$future$weekly_enabled))"success_noop" else "skipped",list(reason=if(isTRUE(cfg$future$daily_enabled)||isTRUE(cfg$future$weekly_enabled))"no_applicable_dates" else "disabled")); if(mode %in% c("full","process","aggregate")) {m<-update_manifest_stage(m,"final_validation","running"); m$final_validation<-final_validate_smoke_run(inv_after,expected,weekly_result,cfg$spatial$template_path);m<-update_manifest_stage(m,"final_validation","success",list(result=m$final_validation))} else m<-update_manifest_stage(m,"final_validation","not_run")
    for(stage in c("plan","download","process","aggregate","estimate","final_validation"))if(is.null(m$stage_results[[stage]]))m<-update_manifest_stage(m,stage,"not_run"); finalize_run_manifest(m,"success")
  },error=function(e){if(!is.null(m)){msg<-conditionMessage(e);failed<-if(grepl("failed_stage=",msg))sub(".*failed_stage=([^[:space:]]+).*","\\1",msg)else if(identical(m$current_stage,"download"))"download"else m$current_stage;m$pipeline_status<-"failed";m$failed_stage<-failed;m$failure_class<-class(e);m$failure_message<-msg;m$current_stage<-failed;m$stage_results[[failed]]<-list(status="failed",failure_message=msg);for(stage in c("plan","download","process","aggregate","estimate","final_validation"))if(is.null(m$stage_results[[stage]]))m$stage_results[[stage]]<-list(status="not_run");finalize_run_manifest(m,"failed");log_stage(m$storage_paths,m$run_id,failed,"failed",paste0("failure_reason=",gsub("\\n"," ",msg)))};stop(e)})
}
