detect_download_format <- function(path) {
  if (!file.exists(path) || file.info(path)$size < 4) return("unknown")
  b <- readBin(path, "raw", n=8); h <- paste(sprintf("%02x", as.integer(b)), collapse=" ")
  if (length(b)>=8 && identical(h, "89 48 44 46 0d 0a 1a 0a")) return("netcdf4_hdf5")
  if (length(b)>=4 && identical(substr(h,1,11), "43 44 46 01")) return("netcdf_classic")
  if (length(b)>=4 && identical(substr(h,1,11), "43 44 46 02")) return("netcdf_classic")
  if (length(b)>=4 && identical(substr(h,1,11), "50 4b 03 04")) return("zip")
  if (length(b)>=4 && identical(substr(h,1,11), "47 52 49 42")) return("grib")
  txt <- tryCatch(rawToChar(readBin(path,"raw",n=min(512,file.info(path)$size))),error=function(e) "")
  if (grepl("<html|<!doctype html",txt,ignore.case=TRUE)) return("html")
  if (grepl("^\\s*[\\[{]",txt)) return("json")
  "unknown"
}
.ncatt <- function(nc,varid,name,default=NA) { z<-tryCatch(ncdf4::ncatt_get(nc,varid,name),error=function(e)list(hasatt=FALSE)); if(isTRUE(z$hasatt))z$value else default }
decode_netcdf_time <- function(values,units,calendar="standard") { if(is.null(units)||length(units)!=1L||is.na(units)||!nzchar(units))stop("NetCDF time units are missing",call.=FALSE);cal<-tolower(calendar %||% "standard");if(!cal%in%c("standard","gregorian","proleptic_gregorian"))stop("Unsupported NetCDF calendar: ",calendar,call.=FALSE);m<-regexec("^(seconds|hours|days)\\s+since\\s+(.+)$",tolower(trimws(units)));z<-regmatches(tolower(trimws(units)),m)[[1]];if(length(z)!=3)stop("Unsupported NetCDF time units: ",units,call.=FALSE);origin_txt<-sub(" z$","",trimws(z[3]),ignore.case=TRUE);origin_txt<-sub("[.]0+$","",origin_txt);origin<-as.POSIXct(origin_txt,tz="UTC",format="%Y-%m-%d %H:%M:%S");if(is.na(origin))origin<-as.POSIXct(origin_txt,tz="UTC",format="%Y-%m-%d");if(is.na(origin))stop("Could not decode NetCDF time origin: ",origin_txt,call.=FALSE);mult<-c(seconds=1,hours=3600,days=86400)[[z[2]]];as.POSIXct(origin+as.numeric(values)*mult,tz="UTC",origin="1970-01-01") }
inspect_netcdf_ncdf4 <- function(path) { if(!requireNamespace("ncdf4",quietly=TRUE))stop("Package 'ncdf4' is required");nc<-ncdf4::nc_open(path);on.exit(ncdf4::nc_close(nc),add=TRUE);vars<-lapply(nc$var,function(v)list(name=v$name,units=.ncatt(nc,v$name,"units",NA_character_),dimensions=vapply(v$dim,function(d)d$name,character(1)),dimension_lengths=vapply(v$dim,function(d)d$len,numeric(1)),fill_value=v$missval,missing_value=.ncatt(nc,v$name,"missing_value",NA_real_),scale_factor=.ncatt(nc,v$name,"scale_factor",1),add_offset=.ncatt(nc,v$name,"add_offset",0)));for(d in setdiff(names(nc$dim),names(vars)))vars[[d]]<-list(name=d,units=nc$dim[[d]]$units,dimensions=d,dimension_lengths=nc$dim[[d]]$len,fill_value=NA_real_,missing_value=NA_real_,scale_factor=1,add_offset=0);dims<-lapply(nc$dim,function(d)list(name=d$name,length=d$len,units=d$units,values=if(d$len<=10000)d$vals else NULL));tv<-intersect(c("valid_time","time"),names(nc$dim));tname<-if(length(tv))tv[[1]]else NULL;vals<-if(!is.null(tname))nc$dim[[tname]]$vals else numeric();tunits<-if(!is.null(tname))nc$dim[[tname]]$units else NA_character_;cal<-if(!is.null(tname)).ncatt(nc,tname,"calendar","standard")else NA_character_;decoded<-if(!is.null(tname))decode_netcdf_time(vals,tunits,cal)else as.POSIXct(character());lonname<-intersect(c("longitude","lon"),names(nc$dim));latname<-intersect(c("latitude","lat"),names(nc$dim));lon<-if(length(lonname))nc$dim[[lonname[[1]]] ]$vals else numeric();lat<-if(length(latname))nc$dim[[latname[[1]]] ]$vals else numeric();list(path=path,format=detect_download_format(path),variables=vars,dimensions=dims,global_attributes=nc$gatts,coordinate_variables=list(longitude=lon,latitude=lat),time_variable=tname,time_units=tunits,calendar=cal,decoded_timestamps=decoded,decoded_dates=as.Date(decoded),longitude_range=range(lon),latitude_range=range(lat),longitude_order=if(length(lon)>1)if(lon[1]<tail(lon,1))"ascending"else"descending"else"single",latitude_order=if(length(lat)>1)if(lat[1]<tail(lat,1))"ascending"else"descending"else"single") }
select_era5_temperature_variable <- function(nc_metadata) { candidates<-intersect(c("t2m","2m_temperature"),names(nc_metadata$variables));if(length(candidates)!=1L)stop("Could not select an unambiguous ERA5 temperature variable",call.=FALSE);v<-nc_metadata$variables[[candidates[[1]]]];if(!tolower(v$units)%in%c("k","kelvin"))stop("Selected temperature variable is not in kelvin",call.=FALSE);candidates[[1]] }
read_era5_daily_with_ncdf4 <- function(path,variable="t2m",expected_dates=NULL,variable_spec=NULL) { md<-inspect_netcdf_ncdf4(path);spec<-variable_spec%||%get_variable_spec(variable);selected<-if(variable%in%names(md$variables)&&identical(spec$id,"era5_mintemp"))variable else resolve_netcdf_variable(md,spec);units_raw<-md$variables[[selected]]$units;if(is.na(units_raw)||!nzchar(units_raw))stop("Selected NetCDF variable units are missing",call.=FALSE);units_norm<-tolower(gsub("\\s+"," ",trimws(units_raw)));compatible<-if(spec$id=="era5_soilmoist")units_norm%in%c("m3 m-3","m^3 m^-3","m3/m3","1")else units_norm%in%c("k","kelvin");if(!compatible)stop("Selected variable has incompatible source units: ",units_raw,call.=FALSE);nc<-ncdf4::nc_open(path);on.exit(ncdf4::nc_close(nc),add=TRUE);lon<-ncdf4::ncvar_get(nc,"longitude");lat<-ncdf4::ncvar_get(nc,"latitude");time<-ncdf4::ncvar_get(nc,md$time_variable);a<-ncdf4::ncvar_get(nc,selected,raw_datavals=TRUE);dims<-vapply(nc$var[[selected]]$dim,function(d)d$name,character(1));perm<-match(c(intersect(c("longitude","lon"),dims)[1],intersect(c("latitude","lat"),dims)[1],md$time_variable),dims);if(anyNA(perm)||length(dim(a))!=3)stop("Selected variable must have longitude, latitude, and time dimensions",call.=FALSE);a<-aperm(a,perm);v<-md$variables[[selected]];fill<-c(v$fill_value,v$missing_value);if(length(fill)&&any(is.finite(fill)))a[a%in%fill]<-NA_real_;sf<-as.numeric(v$scale_factor);ao<-as.numeric(v$add_offset);if(!is.na(sf)&&sf!=1)a<-a*sf;if(!is.na(ao)&&ao!=0)a<-a+ao;dates<-as.Date(decode_netcdf_time(time,md$time_units,md$calendar));if(anyDuplicated(dates))stop("Duplicate decoded NetCDF dates",call.=FALSE);if(!is.null(expected_dates)&&!all(as.Date(expected_dates)%in%dates))stop("Expected dates are absent from NetCDF",call.=FALSE);if(!is.null(expected_dates)&&!all(dates%in%as.Date(expected_dates)))stop("Decoded NetCDF date lies outside expected dates",call.=FALSE);dx<-if(length(lon)>1)median(diff(sort(lon)))else 1;dy<-if(length(lat)>1)median(diff(sort(lat)))else 1;ras<-vector("list",length(dates));for(i in seq_along(dates)){m<-t(a[,,i,drop=TRUE]);if(length(lat)>1&&lat[1]<tail(lat,1))m<-m[nrow(m):1,,drop=FALSE];if(length(lon)>1&&lon[1]>tail(lon,1))m<-m[,ncol(m):1,drop=FALSE];r<-terra::rast(m,extent=terra::ext(min(lon)-abs(dx)/2,max(lon)+abs(dx)/2,min(lat)-abs(dy)/2,max(lat)+abs(dy)/2),crs="EPSG:4326");if(any(lon<0)&&any(lon>180))r<-terra::rotate(r);ras[[i]]<-convert_source_units(r,spec,units_raw)};list(rasters=ras,dates=dates,reader_used="ncdf4",source_format=md$format,selected_variable=selected,selected_variable_alias=selected,source_units=units_raw,decoded_dates=dates,dimension_names=dims,dimension_order=dims,metadata=md,temperature_variable=if(spec$id=="era5_mintemp")selected else NULL,variable_spec=spec,daily_statistic_source="cds_daily_statistics",daily_statistic="mean",subdaily_frequency="6_hourly") }
read_era5_daily_layers <- function(path,expected_dates=NULL,variable_spec=NULL) { spec<-variable_spec%||%get_variable_spec("era5_mintemp");fmt<-detect_download_format(path);if(fmt%in%c("netcdf4_hdf5","netcdf_classic")){if(fmt=="netcdf4_hdf5")return(read_era5_daily_with_ncdf4(path,expected_dates=expected_dates,variable_spec=spec));x<-tryCatch(terra::rast(path),error=function(e)NULL);if(!is.null(x))return(list(rasters=lapply(seq_len(terra::nlyr(x)),function(i)x[[i]]),dates=as.Date(terra::time(x)),reader_used="terra",source_format=fmt,selected_variable=spec$netcdf_variable_names[[1]],selected_variable_alias=spec$netcdf_variable_names[[1]],source_units=spec$source_units,variable_spec=spec));return(read_era5_daily_with_ncdf4(path,expected_dates=expected_dates,variable_spec=spec))};if(fmt=="zip"){ex<-file.path(dirname(path),"extracted");fs::dir_create(ex,recurse=TRUE);normalize_downloaded_file(path,ex);files<-list.files(ex,pattern="\\.nc4?$",full.names=TRUE,recursive=TRUE,ignore.case=TRUE);if(!length(files))stop("ZIP contains no NetCDF files");return(read_era5_daily_layers(files[[1]],expected_dates,spec))};if(fmt=="grib")stop("GRIB dispatch requires a terra/GDAL reader");stop("Unsupported download format: ",fmt," (magic bytes inspected)",call.=FALSE) }
discover_netcdf_files <- function(path) { fmt<-detect_download_format(path);if(fmt%in%c("netcdf4_hdf5","netcdf_classic"))return(path);if(fmt=="zip"){z<-utils::unzip(path,list=TRUE)$Name;return(file.path(dirname(path),z[grepl("\\.nc4?$",z,ignore.case=TRUE)]))};character() }
normalize_downloaded_file <- function(path,extraction_dir) { if(!file.exists(path))stop("Raw file missing: ",path);if(detect_download_format(path)!="zip")return(discover_netcdf_files(path));fs::dir_create(extraction_dir,recurse=TRUE);z<-utils::unzip(path,list=TRUE)$Name;if(any(grepl("(^|/|\\\\)\\.\\.",z)))stop("Unsafe archive paths");utils::unzip(path,exdir=extraction_dir);list.files(extraction_dir,pattern="\\.nc4?$",full.names=TRUE,recursive=TRUE,ignore.case=TRUE) }
inspect_netcdf_file <- function(path) inspect_netcdf_ncdf4(path)
