detect_download_format <- function(path) {
  if (!file.exists(path) || file.info(path)$size < 4) return("unknown")
  b <- readBin(path, "raw", n=8); h <- paste(sprintf("%02x", as.integer(b)), collapse=" ")
  if (length(b) >= 8 && identical(h, "89 48 44 46 0d 0a 1a 0a")) return("netcdf4_hdf5")
  if (length(b) >= 4 && identical(substr(h, 1, 11), "43 44 46 01")) return("netcdf_classic")
  if (length(b) >= 4 && identical(substr(h, 1, 11), "43 44 46 02")) return("netcdf_classic")
  if (length(b) >= 4 && identical(substr(h, 1, 11), "50 4b 03 04")) return("zip")
  if (length(b) >= 4 && identical(substr(h, 1, 11), "47 52 49 42")) return("grib")
  txt <- tryCatch(rawToChar(readBin(path, "raw", n=min(512, file.info(path)$size))), error=function(e) "")
  if (grepl("<html|<!doctype html", txt, ignore.case=TRUE)) return("html")
  if (grepl("^\\s*[\\[{]", txt)) return("json")
  "unknown"
}
.ncatt <- function(nc, varid, name, default=NA) { z <- tryCatch(ncdf4::ncatt_get(nc, varid, name), error=function(e) list(hasatt=FALSE)); if (isTRUE(z$hasatt)) z$value else default }
decode_netcdf_time <- function(values, units, calendar="standard") { if (is.null(units) || length(units) != 1L || is.na(units) || !nzchar(units)) stop("NetCDF time units are missing", call.=FALSE); cal <- tolower(calendar %||% "standard"); if (!cal %in% c("standard", "gregorian", "proleptic_gregorian")) stop("Unsupported NetCDF calendar: ", calendar, call.=FALSE); m <- regexec("^(seconds|hours|days)\\s+since\\s+(.+)$", tolower(trimws(units))); z <- regmatches(tolower(trimws(units)), m)[[1]]; if (length(z) != 3) stop("Unsupported NetCDF time units: ", units, call.=FALSE); origin_txt <- sub(" z$", "", trimws(z[3]), ignore.case=TRUE); origin_txt <- sub("[.]0+$", "", origin_txt); origin <- as.POSIXct(origin_txt, tz="UTC", format="%Y-%m-%d %H:%M:%S"); if (is.na(origin)) origin <- as.POSIXct(origin_txt, tz="UTC", format="%Y-%m-%d"); if (is.na(origin)) stop("Could not decode NetCDF time origin: ", origin_txt, call.=FALSE); mult <- c(seconds=1, hours=3600, days=86400)[[z[2]]]; as.POSIXct(origin + as.numeric(values) * mult, tz="UTC", origin="1970-01-01") }
inspect_netcdf_ncdf4 <- function(path) {
  if (!requireNamespace("ncdf4", quietly=TRUE)) stop("Package 'ncdf4' is required")
  nc <- ncdf4::nc_open(path); on.exit(ncdf4::nc_close(nc), add=TRUE)
  vars <- lapply(nc$var, function(v) list(name=v$name, units=.ncatt(nc, v$name, "units", NA_character_), dimensions=vapply(v$dim, function(d) d$name, character(1)), dimension_lengths=vapply(v$dim, function(d) d$len, numeric(1)), fill_value=v$missval, missing_value=.ncatt(nc, v$name, "missing_value", NA_real_), scale_factor=.ncatt(nc, v$name, "scale_factor", 1), add_offset=.ncatt(nc, v$name, "add_offset", 0)))
  for (d in setdiff(names(nc$dim), names(vars))) vars[[d]] <- list(name=d, units=nc$dim[[d]]$units, dimensions=d, dimension_lengths=nc$dim[[d]]$len, fill_value=NA_real_, missing_value=NA_real_, scale_factor=1, add_offset=0)
  dims <- lapply(nc$dim, function(d) list(name=d$name, length=d$len, units=d$units, values=if (d$len <= 10000) d$vals else NULL))
  tname <- intersect(c("valid_time", "time"), names(nc$dim)); tname <- if (length(tname)) tname[[1]] else NA_character_
  lonname <- intersect(c("longitude", "lon"), names(nc$dim)); lonname <- if (length(lonname)) lonname[[1]] else NA_character_
  latname <- intersect(c("latitude", "lat"), names(nc$dim)); latname <- if (length(latname)) latname[[1]] else NA_character_
  vals <- if (!is.na(tname)) nc$dim[[tname]]$vals else numeric(); tunits <- if (!is.na(tname)) nc$dim[[tname]]$units else NA_character_; cal <- if (!is.na(tname)) .ncatt(nc, tname, "calendar", "standard") else NA_character_; decoded <- if (!is.na(tname)) decode_netcdf_time(vals, tunits, cal) else as.POSIXct(character())
  lon <- if (!is.na(lonname)) nc$dim[[lonname]]$vals else numeric(); lat <- if (!is.na(latname)) nc$dim[[latname]]$vals else numeric()
  list(path=path, format=detect_download_format(path), variables=vars, dimensions=dims, global_attributes=nc$gatts, coordinate_variables=list(longitude=lon, latitude=lat), longitude_variable=lonname, latitude_variable=latname, time_variable=tname, time_units=tunits, calendar=cal, decoded_timestamps=decoded, decoded_dates=as.Date(decoded), longitude_range=if (length(lon)) range(lon) else numeric(), latitude_range=if (length(lat)) range(lat) else numeric(), longitude_order=if (length(lon) > 1) if (lon[1] < tail(lon,1)) "ascending" else "descending" else "single", latitude_order=if (length(lat) > 1) if (lat[1] < tail(lat,1)) "ascending" else "descending" else "single")
}
select_era5_temperature_variable <- function(nc_metadata) { candidates <- intersect(c("t2m", "2m_temperature"), names(nc_metadata$variables)); if (length(candidates) != 1L) stop("Could not select an unambiguous ERA5 temperature variable", call.=FALSE); v <- nc_metadata$variables[[candidates[[1]]]]; if (!identical(normalize_source_units(v$units), "K")) stop("Selected temperature variable is not in kelvin", call.=FALSE); candidates[[1]] }
read_era5_daily_with_ncdf4 <- function(path, variable="t2m", expected_dates=NULL, variable_spec=NULL) {
  md <- inspect_netcdf_ncdf4(path); spec <- variable_spec %||% get_variable_spec(variable); selected <- resolve_netcdf_variable(md, spec); v <- md$variables[[selected]]; units_original <- v$units; units_normalized <- normalize_source_units(units_original); expected_units <- if (spec$id == "era5_soilmoist") "m3 m-3" else "K"; if (!identical(units_normalized, expected_units)) stop("Selected variable has incompatible source units: ", units_original, call.=FALSE)
  if (anyNA(c(md$longitude_variable, md$latitude_variable, md$time_variable))) stop("NetCDF coordinate or time dimension is missing", call.=FALSE)
  nc <- ncdf4::nc_open(path); on.exit(ncdf4::nc_close(nc), add=TRUE); lon <- ncdf4::ncvar_get(nc, md$longitude_variable); lat <- ncdf4::ncvar_get(nc, md$latitude_variable); time <- ncdf4::ncvar_get(nc, md$time_variable); a <- ncdf4::ncvar_get(nc, selected, raw_datavals=TRUE); dims <- vapply(nc$var[[selected]]$dim, function(d) d$name, character(1)); perm <- match(c(md$longitude_variable, md$latitude_variable, md$time_variable), dims); if (anyNA(perm) || length(dim(a)) != 3L) stop("Selected variable must have longitude, latitude, and time dimensions", call.=FALSE); a <- aperm(a, perm)
  fill <- c(v$fill_value, v$missing_value); if (length(fill) && any(is.finite(fill))) a[a %in% fill] <- NA_real_; sf <- as.numeric(v$scale_factor); ao <- as.numeric(v$add_offset); if (!is.na(sf) && sf != 1) a <- a * sf; if (!is.na(ao) && ao != 0) a <- a + ao; dates <- as.Date(decode_netcdf_time(time, md$time_units, md$calendar)); expected_dates <- if (is.null(expected_dates)) NULL else sort(unique(as.Date(expected_dates))); if (anyDuplicated(dates)) stop("Duplicate decoded NetCDF dates", call.=FALSE); if (!is.null(expected_dates) && (!identical(sort(dates), expected_dates) || length(dates) != length(expected_dates))) stop("Decoded dates do not exactly match expected dates", call.=FALSE)
  dx <- if (length(lon) > 1) median(diff(sort(lon))) else 1; dy <- if (length(lat) > 1) median(diff(sort(lat))) else 1; ras <- vector("list", length(dates)); for (i in seq_along(dates)) { mm <- t(a[,,i,drop=TRUE]); if (length(lat) > 1 && lat[1] < tail(lat,1)) mm <- mm[nrow(mm):1,,drop=FALSE]; if (length(lon) > 1 && lon[1] > tail(lon,1)) mm <- mm[,ncol(mm):1,drop=FALSE]; r <- terra::rast(mm, extent=terra::ext(min(lon)-abs(dx)/2,max(lon)+abs(dx)/2,min(lat)-abs(dy)/2,max(lat)+abs(dy)/2), crs="EPSG:4326"); if (any(lon < 0) && any(lon > 180)) r <- terra::rotate(r); ras[[i]] <- convert_source_units(r, spec, units_original) }
  list(rasters=ras, dates=dates, reader_used="ncdf4", source_format=md$format, selected_variable=selected, selected_variable_alias=selected, source_units=units_original, source_units_original=units_original, source_units_normalized=units_normalized, output_units=spec$output_units, unit_conversion=spec$unit_conversion, decoded_dates=dates, dimension_names=dims, dimension_lengths=unname(v$dimension_lengths), dimension_order=dims, latitude_direction=md$latitude_order, longitude_convention=if (all(lon >= 0)) "0_360" else "-180_180", metadata=md, temperature_variable=if (spec$id == "era5_mintemp") selected else NULL, variable_spec=spec, daily_statistic_source="cds_daily_statistics", daily_statistic=spec$daily_statistic, subdaily_frequency=spec$frequency)
}
read_era5_daily_layers <- function(path, expected_dates=NULL, variable_spec=NULL) { spec <- variable_spec %||% get_variable_spec("era5_mintemp"); fmt <- detect_download_format(path); if (fmt %in% c("netcdf4_hdf5", "netcdf_classic")) { if (fmt == "netcdf4_hdf5") return(read_era5_daily_with_ncdf4(path, expected_dates=expected_dates, variable_spec=spec)); x <- tryCatch(terra::rast(path), error=function(e) NULL); if (!is.null(x)) return(list(rasters=lapply(seq_len(terra::nlyr(x)), function(i) x[[i]]), dates=as.Date(terra::time(x)), reader_used="terra", source_format=fmt, selected_variable=spec$netcdf_variable_names[[1]], selected_variable_alias=spec$netcdf_variable_names[[1]], source_units=spec$source_units, source_units_original=spec$source_units, source_units_normalized=normalize_source_units(spec$source_units), output_units=spec$output_units, unit_conversion=spec$unit_conversion, variable_spec=spec)); return(read_era5_daily_with_ncdf4(path, expected_dates=expected_dates, variable_spec=spec)) }; if (fmt == "zip") { ex <- file.path(dirname(path), "extracted"); fs::dir_create(ex, recurse=TRUE); normalize_downloaded_file(path, ex); files <- list.files(ex, pattern="\\.nc4?$", full.names=TRUE, recursive=TRUE, ignore.case=TRUE); if (!length(files)) stop("ZIP contains no NetCDF files"); return(read_era5_daily_layers(files[[1]], expected_dates, spec)) }; if (fmt == "grib") stop("GRIB dispatch requires a terra/GDAL reader"); stop("Unsupported download format: ", fmt, " (magic bytes inspected)", call.=FALSE) }
discover_netcdf_files <- function(path) { fmt <- detect_download_format(path); if (fmt %in% c("netcdf4_hdf5", "netcdf_classic")) return(path); if (fmt == "zip") { z <- utils::unzip(path, list=TRUE)$Name; return(file.path(dirname(path), z[grepl("\\.nc4?$", z, ignore.case=TRUE)])) }; character() }
normalize_downloaded_file <- function(path, extraction_dir) { if (!file.exists(path)) stop("Raw file missing: ", path); if (detect_download_format(path) != "zip") return(discover_netcdf_files(path)); fs::dir_create(extraction_dir, recurse=TRUE); z <- utils::unzip(path, list=TRUE)$Name; if (any(grepl("(^|/|\\\\)\\.\\.", z))) stop("Unsafe archive paths"); utils::unzip(path, exdir=extraction_dir); list.files(extraction_dir, pattern="\\.nc4?$", full.names=TRUE, recursive=TRUE, ignore.case=TRUE) }
inspect_netcdf_file <- function(path) inspect_netcdf_ncdf4(path)
