template_crs_parameters <- function(template) {
  p <- terra::crs(template, proj=TRUE)
  getp <- function(key) { z <- regexec(paste0("[+]", key, "=([-+0-9.eE]+)"), p); m <- regmatches(p,z)[[1]]; if(length(m)) as.numeric(m[2]) else NA_real_ }
  units <- sub(".*[+]units=([^ ]+).*", "\\1", p); if(identical(units,p)) units <- NA_character_
  list(projection=if(grepl("[+]proj=aea",p)) "aea" else NA_character_, datum=if(grepl("[+]datum=WGS84",p,ignore.case=TRUE)) "WGS84" else NA_character_, units=units, unit_conversion_factor=if(identical(units,"km")) 1000 else if(identical(units,"m")) 1 else NA_real_, central_meridian=getp("lon_0"), latitude_of_origin=getp("lat_0"), latitude_of_first_standard_parallel=getp("lat_1"), latitude_of_second_standard_parallel=getp("lat_2"), false_easting=getp("x_0"), false_northing=getp("y_0"), proj_string=p)
}
validate_template_crs <- function(template, expected_crs, tolerance=0.001) {
  p <- terra::crs(template, proj=TRUE); if(!nzchar(p)) stop("Template CRS is missing", call.=FALSE); if(terra::is.lonlat(template)) stop("Template CRS must be projected", call.=FALSE)
  got <- template_crs_parameters(template); numeric_fields <- c("central_meridian","latitude_of_origin","latitude_of_first_standard_parallel","latitude_of_second_standard_parallel","false_easting","false_northing")
  if(is.na(got$projection)||got$projection!="aea") stop("Template CRS is not Albers equal-area",call.=FALSE); if(is.na(got$datum)||got$datum!="WGS84") stop("Template CRS datum is not WGS84",call.=FALSE); if(is.na(got$units)||got$units!="km"||abs(got$unit_conversion_factor-1000)>tolerance*1000) stop("Template CRS must use kilometer native units",call.=FALSE)
  for(n in numeric_fields) if(is.na(got[[n]])||is.null(expected_crs[[n]])||abs(got[[n]]-as.numeric(expected_crs[[n]]))>tolerance) stop("Template CRS parameter does not match expected: ",n,call.=FALSE)
  list(valid=TRUE, parameters=got)
}
template_fingerprint <- function(path_or_template) { r <- if(is.character(path_or_template)) terra::rast(path_or_template) else path_or_template; vals <- terra::values(r,mat=FALSE); list(crs=terra::crs(r,proj=TRUE), extent=as.vector(terra::ext(r)), resolution=as.numeric(terra::res(r)), origin=as.numeric(terra::origin(r)), rows=terra::nrow(r), columns=terra::ncol(r), layers=terra::nlyr(r), non_na_count=sum(!is.na(vals)), na_pattern_hash=digest::digest(is.na(vals),algo="xxhash32"), value_hash=digest::digest(vals,algo="xxhash32"), file_checksum=if(is.character(path_or_template)) unname(tools::md5sum(path_or_template)) else NA_character_)
}
validate_template_geometry <- function(template, expected, tolerance=0.001) { if(terra::nrow(template)!=expected$rows||terra::ncol(template)!=expected$columns||terra::nlyr(template)!=expected$layers) stop("Template dimensions do not match expected",call.=FALSE); if(any(abs(terra::res(template)-c(expected$resolution$x,expected$resolution$y))>tolerance)) stop("Template resolution does not match expected",call.=FALSE); e<-as.vector(terra::ext(template)); ee<-c(expected$extent$xmin,expected$extent$xmax,expected$extent$ymin,expected$extent$ymax); if(any(abs(e-ee)>tolerance)) stop("Template extent does not match expected",call.=FALSE); vals<-terra::values(template,mat=FALSE); if(!any(!is.na(vals))) stop("Template is all NA",call.=FALSE); if(any(vals[!is.na(vals)]!=1)) stop("Template non-NA mask values must equal 1",call.=FALSE); if(all(!is.na(vals))) stop("Template mask is globally non-NA",call.=FALSE); TRUE }
bbox_to_cds_area <- function(bbox_path, buffer_degrees=0.25) { if(!requireNamespace("sf",quietly=TRUE)) stop("Package 'sf' is required"); b<-sf::st_read(bbox_path,quiet=TRUE); if(is.na(sf::st_crs(b))) stop("Bounding box has no CRS"); b<-sf::st_transform(sf::st_make_valid(b),4326); e<-sf::st_bbox(sf::st_union(b)); west<-max(-180,unname(e[["xmin"]])-buffer_degrees); east<-min(180,unname(e[["xmax"]])+buffer_degrees); south<-max(-90,unname(e[["ymin"]])-buffer_degrees); north<-min(90,unname(e[["ymax"]])+buffer_degrees); if(north<=south||east<=west) stop("Invalid CDS area"); c(north=north,west=west,south=south,east=east) }
diagnose_spatial_domain <- function(template_path,bbox_path,config=NULL) { if(!requireNamespace("terra",quietly=TRUE)||!requireNamespace("sf",quietly=TRUE)) stop("terra and sf are required"); r<-terra::rast(template_path); b<-sf::st_make_valid(sf::st_read(bbox_path,quiet=TRUE)); if(is.na(sf::st_crs(b))) stop("Bounding box has no CRS"); b4326<-sf::st_transform(b,4326); area<-bbox_to_cds_area(bbox_path,if(is.null(config)) 0.25 else config$spatial$api_bbox_buffer_degrees); has<-nzchar(terra::crs(r)); fp<-template_fingerprint(template_path); pars<-if(has) template_crs_parameters(r) else list(); overlap_extent<-if(has) { bt<-sf::st_as_sfc(sf::st_bbox(r)); any(sf::st_intersects(b4326,sf::st_transform(bt,4326),sparse=FALSE)) } else NA; btemp<-if(has) sf::st_transform(b,terra::crs(r)) else NULL; extent_prop<-if(has) { ep<-sf::st_as_sfc(sf::st_bbox(r)); as.numeric(sf::st_area(sf::st_intersection(sf::st_union(btemp),ep))/sf::st_area(sf::st_union(btemp))) } else NA; mask_overlap<-if(has) { inside<-terra::vect(btemp); sum(terra::extract(r,inside)[,2]==1,na.rm=TRUE)>0 } else NA; list(template_path=normalizePath(template_path,winslash="/"),template_file_checksum=unname(tools::md5sum(template_path)),crs_present=has,template_crs=if(has) terra::crs(r,proj=FALSE) else NA_character_,template_crs_wkt=if(has) terra::crs(r) else NA_character_,template_is_geographic=if(has) terra::is.lonlat(r) else NA,projection_method=pars$projection%||%NA_character_,datum=pars$datum%||%NA_character_,linear_units=pars$units%||%NA_character_,linear_unit_conversion_factor=pars$unit_conversion_factor%||%NA_real_,central_meridian=pars$central_meridian%||%NA_real_,latitude_of_origin=pars$latitude_of_origin%||%NA_real_,standard_parallels=c(pars$latitude_of_first_standard_parallel%||%NA_real_,pars$latitude_of_second_standard_parallel%||%NA_real_),false_easting=pars$false_easting%||%NA_real_,false_northing=pars$false_northing%||%NA_real_,extent=as.vector(terra::ext(r)),resolution=terra::res(r),origin=terra::origin(r),dimensions=c(rows=terra::nrow(r),columns=terra::ncol(r),layers=terra::nlyr(r)),ncell=terra::ncell(r),non_na_count=fp$non_na_count,minimum=as.numeric(terra::global(r,"min",na.rm=TRUE)[1,1]),maximum=as.numeric(terra::global(r,"max",na.rm=TRUE)[1,1]),bbox_crs=sf::st_crs(b)$wkt,bbox_valid=all(sf::st_is_valid(b)),boundary_extent_4326=as.vector(sf::st_bbox(b4326)),boundary_extent_template=if(has) as.vector(sf::st_bbox(btemp)) else NA,proportion_boundary_within_template_extent=extent_prop,template_boundary_overlap=overlap_extent,mask_overlap=mask_overlap,proposed_cds_area=area,template_fingerprint=fp) }
