validate_raster_against_template <- function(raster, template, value_range=c(-100,70), exact_geometry=TRUE, variable_spec=NULL) {
  r <- tryCatch(if(is.character(raster)) terra::rast(raster) else raster, error=function(e)e)
  if(inherits(r,"error")) return(list(valid=FALSE,message=conditionMessage(r)))
  if(terra::nlyr(r)!=1) return(list(valid=FALSE,message="expected one layer"))
  if(exact_geometry) { same<-identical(terra::crs(r),terra::crs(template))&&all(abs(as.vector(terra::ext(r))-as.vector(terra::ext(template)))<1e-9)&&all(abs(as.numeric(terra::res(r))-as.numeric(terra::res(template)))<1e-9)&&terra::nrow(r)==terra::nrow(template)&&terra::ncol(r)==terra::ncol(template)&&all(abs(as.numeric(terra::origin(r))-as.numeric(terra::origin(template)))<1e-9);if(!same)return(list(valid=FALSE,message="geometry does not match template")) }
  v<-as.numeric(terra::values(r,mat=FALSE));v<-v[is.finite(v)];if(!length(v))return(list(valid=FALSE,message="all values are NA"));if(any(v<value_range[1]|v>value_range[2]))return(list(valid=FALSE,message="values outside configured range"));stats<-if(!is.null(variable_spec))validate_variable_values(v,variable_spec)else NULL;list(valid=TRUE,message="ok",minimum=min(v),maximum=max(v),n=length(v),statistics=stats)
}
validate_template_coverage <- function(output,template,require_complete=TRUE,diagnostic_dir=NULL,date=NULL,prefix=NULL) {out<-if(is.character(output))terra::rast(output)else output;template_valid<-!is.na(terra::values(template,mat=FALSE));output_valid<-!is.na(terra::values(out,mat=FALSE));if(length(template_valid)!=length(output_valid))stop("Output and template cell counts differ",call.=FALSE);missing_inside<-template_valid&!output_valid;outside_mask<-!template_valid&output_valid;idx<-which(missing_inside);xy<-if(length(idx))terra::xyFromCell(template,idx)else matrix(numeric(),ncol=2);result<-list(template_non_na=sum(template_valid),output_non_na=sum(output_valid),missing_inside_count=sum(missing_inside),outside_mask_count=sum(outside_mask),complete=!any(missing_inside|outside_mask),missing_cell_indices=idx,missing_x_range=if(length(idx))range(xy[,1])else c(NA_real_,NA_real_),missing_y_range=if(length(idx))range(xy[,2])else c(NA_real_,NA_real_));if(!is.null(diagnostic_dir)&&!result$complete){fs::dir_create(diagnostic_dir,recurse=TRUE);stem<-if(is.null(date))"output"else paste0(prefix%||%"mintemp","_",format(as.Date(date),"%Y-%m-%d"));m<-template;o<-template;terra::values(m)<-ifelse(missing_inside,1,NA);terra::values(o)<-ifelse(outside_mask,1,NA);result$coverage_diagnostic_paths<-c(missing_inside=file.path(diagnostic_dir,paste0(stem,"_missing_inside.tif")),outside_mask=file.path(diagnostic_dir,paste0(stem,"_outside_mask.tif")));terra::writeRaster(m,result$coverage_diagnostic_paths[[1]],overwrite=TRUE);terra::writeRaster(o,result$coverage_diagnostic_paths[[2]],overwrite=TRUE)}else result$coverage_diagnostic_paths<-character();if(isTRUE(require_complete)&&!result$complete)stop(sprintf("Template coverage incomplete: missing_inside_count=%d outside_mask_count=%d",result$missing_inside_count,result$outside_mask_count),call.=FALSE);result }
validate_daily_output <- function(path,expected_date,template,config,diagnostic_dir=NULL,variable_spec=NULL) {spec<-variable_spec%||%get_variable_spec(config$project$dataset_id,config);p<-parse_grid_filename(path,spec$daily_filename_prefix);if(!p$valid||p$timestep!="daily"||p$date!=as.Date(expected_date))return(list(valid=FALSE,message="filename date mismatch"));g<-tryCatch(validate_template_coverage(path,template,isTRUE(config$spatial$require_complete_template_coverage%||%TRUE),diagnostic_dir,expected_date),error=function(e)e);if(inherits(g,"error"))return(list(valid=FALSE,message=conditionMessage(g),coverage=g));v<-validate_raster_against_template(path,template,spec$hard_valid_range,config$validation$require_exact_template_geometry,spec);v$coverage<-g;v}
validate_weekly_output <- function(path,expected_iso_year,expected_iso_week,template=NULL,config=NULL,variable_spec=NULL) {if(is.null(config)&&is.list(template)){config<-template;template<-terra::rast(path)};spec<-variable_spec%||%get_variable_spec(config$project$dataset_id,config);parse_path<-if(endsWith(tolower(path),".tmp.tif"))paste0(substr(path,1L,nchar(path)-8L),".tif")else path;p<-parse_grid_filename(parse_path,spec$weekly_filename_prefix);if(!p$valid||p$timestep!="weekly"||p$iso_year!=as.integer(expected_iso_year)||p$iso_week!=as.integer(expected_iso_week))return(list(valid=FALSE,message="filename week mismatch"));validate_raster_against_template(path,template,spec$hard_valid_range,config$validation$require_exact_template_geometry,spec)}
