iso_week_start <- function(x) {
  x <- as.Date(x)
  if (anyNA(x)) stop("Dates contain missing or invalid values.", call.=FALSE)
  x - (as.integer(strftime(x, "%u")) - 1L)
}
empty_week_assessment <- function() data.frame(iso_year=integer(),iso_week=integer(),week_id=character(),week_start=as.Date(character()),week_end=as.Date(character()),expected_dates=I(list()),available_dates=I(list()),missing_dates=I(list()),available_count=integer(),expected_count=integer(),complete=logical(),stringsAsFactors=FALSE)
identify_affected_iso_weeks <- function(dates) { d <- as.Date(dates); if(!length(d)) return(character()); unique(format(iso_week_start(d), "%G-W%V")) }
assess_iso_week_completeness <- function(dates) {
  raw_dates <- as.Date(dates); if(!length(raw_dates)) return(empty_week_assessment()); if(anyNA(raw_dates)) stop("Dates contain missing or invalid values.",call.=FALSE); d <- sort(unique(raw_dates)); groups <- split(d, iso_week_start(d))
  do.call(rbind,lapply(names(groups),function(start_text) { week_start<-as.Date(start_text); week_end<-week_start+6L; stopifnot(length(week_start)==1L,length(week_end)==1L,!is.na(week_start),!is.na(week_end),week_start<=week_end); expected<-seq.Date(week_start,week_end,by="day"); available<-sort(unique(groups[[start_text]])); missing<-setdiff(expected,available); data.frame(iso_year=as.integer(format(week_start,"%G")),iso_week=as.integer(format(week_start,"%V")),week_id=format(week_start,"%G-W%V"),week_start=week_start,week_end=week_end,expected_dates=I(list(expected)),available_dates=I(list(available)),missing_dates=I(list(missing)),available_count=length(available),expected_count=7L,complete=!length(missing),stringsAsFactors=FALSE)}))
}
aggregate_daily_to_weekly <- function(daily_dir,weekly_dir,prefix="mintemp",iso_weeks=NULL,require_complete_week=TRUE,overwrite=TRUE,template_path,rebuild_all=FALSE,inventory=NULL,inventory_source="post_process") {
  inv <- inventory %||% inventory_grid_directory(daily_dir,prefix,"daily",FALSE); if("observed_valid"%in%names(inv)) inv<-inv[inv$observed_valid%in%TRUE,,drop=FALSE] else inv<-inv[inv$valid&!inv$estimated,,drop=FALSE]; inv<-inv[!is.na(inv$date)&!inv$estimated,,drop=FALSE]; if(!nrow(inv))return(list(status="success_noop",written=character(),reused=character(),incomplete_weeks=data.frame(),complete_weeks=character(),failed=character(),reason="no_valid_daily_products",inventory_source=inventory_source,inventory_rows_received=nrow(inventory%||%inv),valid_daily_rows_received=0L,valid_daily_dates_received=character()))
  inv$date<-normalize_date_vector(inv$date,"inventory_dates"); if(anyDuplicated(format(inv$date,"%Y-%m-%d")))stop("Duplicate valid observed daily dates cannot be aggregated",call.=FALSE); if(rebuild_all||is.null(iso_weeks))iso_weeks<-identify_affected_iso_weeks(inv$date); assessment<-assess_iso_week_completeness(inv$date); assessment<-assessment[assessment$week_id%in%iso_weeks,,drop=FALSE]; incomplete<-assessment[!assessment$complete,,drop=FALSE]; complete<-assessment[assessment$complete,,drop=FALSE]; if(isTRUE(require_complete_week)&&nrow(incomplete)>0L&&nrow(complete)==0L)return(list(status="success_noop",written=character(),reused=character(),incomplete_weeks=incomplete,complete_weeks=complete$week_id,failed=character(),reason="incomplete_week",inventory_source=inventory_source,inventory_rows_received=nrow(inventory),valid_daily_rows_received=nrow(inv),valid_daily_dates_received=format(inv$date,"%Y-%m-%d")))
  template<-terra::rast(template_path);fs::dir_create(weekly_dir,recurse=TRUE);written<-reused<-failed<-character();selected_paths<-list();match_records<-list()
  for(i in seq_len(nrow(complete))) { w<-complete$week_id[i]; expected_dates<-normalize_date_vector(complete$expected_dates[[i]],"expected_dates"); inventory_dates<-normalize_date_vector(inv$date,"inventory_dates"); expected_keys<-format(expected_dates,"%Y-%m-%d"); inventory_keys<-format(inventory_dates,"%Y-%m-%d"); if(length(expected_keys)!=7L||anyDuplicated(expected_keys))stop("Complete ISO week ",w," does not contain seven unique expected dates.",call.=FALSE); match_counts<-vapply(expected_keys,function(key)sum(inventory_keys==key),integer(1));match_records[[w]]<-match_counts;if(!all(match_counts==1L))stop("Expected exactly one valid daily raster per date for ",w,". Counts: ",paste(paste0(expected_keys,"=",match_counts),collapse=", "),call.=FALSE);selected_indices<-match(expected_keys,inventory_keys);week_rows<-inv[selected_indices,,drop=FALSE];stopifnot(nrow(week_rows)==7L,identical(format(normalize_date_vector(week_rows$date),"%Y-%m-%d"),expected_keys));daily_paths<-week_rows$path;for(path in daily_paths){r<-terra::rast(path);if(!terra::compareGeom(r,template,stopOnError=FALSE))stop("Daily raster geometry does not match the template: ",path,call.=FALSE);validate_template_coverage(r,template,TRUE)};daily_stack<-terra::rast(daily_paths);weekly<-terra::app(daily_stack,fun=min,na.rm=TRUE);out<-file.path(weekly_dir,format_weekly_filename(prefix,complete$iso_year[i],complete$iso_week[i]));selected_paths[[w]]<-daily_paths;if(file.exists(out)&&!overwrite)reused<-c(reused,out)else{tmp<-paste0(out,".tmp.tif");terra::writeRaster(weekly,tmp,overwrite=TRUE,wopt=list(datatype="FLT4S",gdal=c("COMPRESS=DEFLATE","PREDICTOR=3","TILED=YES")));if(!file.exists(tmp))stop("Weekly temporary output was not created: ",w,call.=FALSE);if(file.exists(out))unlink(out);if(!file.rename(tmp,out))stop("Could not promote weekly output: ",out,call.=FALSE);check<-validate_weekly_output(out,complete$iso_year[i],complete$iso_week[i],template,list(project=list(output_prefix=prefix),validation=list(minimum_celsius=-100,maximum_celsius=70,require_exact_template_geometry=TRUE)));if(!check$valid)stop("Weekly validation failed: ",w,"; ",check$message,call.=FALSE);validate_template_coverage(out,template,TRUE);written<-c(written,out)};est<-file.path(weekly_dir,format_weekly_filename(prefix,complete$iso_year[i],complete$iso_week[i],TRUE));if(file.exists(est))unlink(est)}
  list(status=if(length(written)||length(reused))"success"else"success_noop",written=written,reused=reused,incomplete_weeks=incomplete,complete_weeks=complete$week_id,failed=failed,reason=if(nrow(incomplete))"some_incomplete_weeks"else NULL,inventory_source=inventory_source,inventory_rows_received=nrow(inventory%||%inv),valid_daily_rows_received=nrow(inv),valid_daily_dates_received=format(inv$date,"%Y-%m-%d"),expected_dates=if(length(match_records))lapply(complete$expected_dates,normalize_date_vector)else list(),match_counts=match_records,selected_daily_paths=selected_paths)
}
