identify_affected_iso_weeks <- function(dates) unique(format(as.Date(dates),"%G-W%V"))

assess_iso_week_completeness <- function(dates) {
  d <- sort(unique(as.Date(dates))); if(anyNA(d)) stop("Invalid dates cannot be assessed",call.=FALSE); if(!length(d)) return(data.frame(iso_year=integer(),iso_week=integer(),week_id=character(),week_start=as.Date(character()),week_end=as.Date(character()),expected_dates=I(list()),available_dates=I(list()),missing_dates=I(list()),available_count=integer(),expected_count=integer(),complete=logical(),stringsAsFactors=FALSE))
  ids <- sort(unique(format(d,"%G-W%V"))); rows <- lapply(ids,function(id) { monday <- ISOweek::ISOweek2date(paste0(id,"-1")); expected <- seq(monday,monday+6,by="day"); available <- d[d %in% expected]; missing <- setdiff(expected,available); data.frame(iso_year=as.integer(substr(id,1,4)),iso_week=as.integer(substr(id,7,8)),week_id=id,week_start=monday,week_end=monday+6,expected_dates=I(list(expected)),available_dates=I(list(available)),missing_dates=I(list(missing)),available_count=length(available),expected_count=7L,complete=length(missing)==0L,stringsAsFactors=FALSE) })
  do.call(rbind,rows)
}

aggregate_daily_to_weekly <- function(daily_dir,weekly_dir,prefix="mintemp",iso_weeks=NULL,require_complete_week=TRUE,overwrite=TRUE,template_path,rebuild_all=FALSE,inventory=NULL) {
  inv <- inventory %||% inventory_grid_directory(daily_dir,prefix,"daily",FALSE); if("observed_valid" %in% names(inv)) inv <- inv[inv$observed_valid %in% TRUE,,drop=FALSE] else inv <- inv[inv$valid & !inv$estimated,,drop=FALSE]; inv <- inv[!is.na(inv$date) & !inv$estimated,,drop=FALSE]; if(!nrow(inv)) return(list(status="success_noop",written=character(),reused=character(),incomplete_weeks=data.frame(),complete_weeks=character(),failed=character(),reason="no_valid_daily_products"))
  if(anyDuplicated(inv$date)) stop("Duplicate valid observed daily dates cannot be aggregated",call.=FALSE); if(rebuild_all || is.null(iso_weeks)) iso_weeks <- identify_affected_iso_weeks(inv$date); assess <- assess_iso_week_completeness(inv$date); assess <- assess[assess$week_id %in% iso_weeks,,drop=FALSE]; incomplete <- assess[!assess$complete,,drop=FALSE]; complete <- assess[assess$complete,,drop=FALSE]; if(isTRUE(require_complete_week) && nrow(incomplete) > 0L && nrow(complete)==0L) return(list(status="success_noop",written=character(),reused=character(),incomplete_weeks=incomplete,complete_weeks=complete$week_id,failed=character(),reason="incomplete_week"))
  template <- terra::rast(template_path); fs::dir_create(weekly_dir,recurse=TRUE); written <- reused <- failed <- character()
  for(i in seq_len(nrow(complete))) { w <- complete$week_id[i]; dates <- unlist(complete$expected_dates[i],use.names=FALSE); rows <- inv[inv$date %in% dates,,drop=FALSE]; if(nrow(rows)!=7L || anyDuplicated(rows$date)) stop("Expected exactly one valid daily raster per date for ",w,call.=FALSE); rows <- rows[match(dates,rows$date),,drop=FALSE]; if(anyNA(rows$path)) stop("Missing daily raster path for ",w,call.=FALSE); ras <- terra::rast(rows$path); if(terra::nlyr(ras)!=7L) stop("Expected seven daily layers for ",w,call.=FALSE); for(j in seq_len(terra::nlyr(ras))) { if(!validate_raster_against_template(ras[[j]],template,c(-100,70),TRUE)$valid) stop("Invalid input raster for ",w,call.=FALSE); validate_template_coverage(ras[[j]],template,TRUE) }; z <- terra::app(ras,min,na.rm=TRUE); out <- file.path(weekly_dir,format_weekly_filename(prefix,complete$iso_year[i],complete$iso_week[i])); if(file.exists(out) && !overwrite) reused <- c(reused,out) else { terra::writeRaster(z,out,overwrite=TRUE,wopt=list(datatype="FLT4S",gdal=c("COMPRESS=DEFLATE","PREDICTOR=3","TILED=YES"))); if(!validate_weekly_output(out,complete$iso_year[i],complete$iso_week[i],list(project=list(output_prefix=prefix),validation=list(minimum_celsius=-100,maximum_celsius=70,require_exact_template_geometry=TRUE)))$valid) stop("Weekly validation failed: ",w,call.=FALSE); written <- c(written,out) }; est <- file.path(weekly_dir,format_weekly_filename(prefix,complete$iso_year[i],complete$iso_week[i],TRUE)); if(file.exists(est)) unlink(est) }
  list(status=if(length(written)||length(reused)) "success" else "success_noop",written=written,reused=reused,incomplete_weeks=incomplete,complete_weeks=complete$week_id,failed=failed,reason=if(nrow(incomplete)) "some_incomplete_weeks" else NULL)
}
